### ISSUE TITLE
SetLogMode doesn't show data

### ISSUE THREAD

**Issue by carlos-emendes** [pyqtgraph/pyqtgraph#1357] opened 2020-09-04 14:59 UTC
### Short description
A array with random values, when plotted , it show's normally, although, when the scale to Logy is set, the data disappear 

### Code to reproduce
import numpy as np
import pyqtgraph as pg

data=[0,0,1,2,145,2324,56464,5,2,1,0,1]
p1=pg.plot(title="test")
p1.plot(data,pen='b')

### Expected behavior
display log data

### Real behavior
data disappear

**Comment by ixjlyons** [comment] 2020-09-17 06:02
If you remove the zeros in the array (or add a small offset), it should work now (with #1364 just merged). However, even with zeros, the entire plot shouldn't disappear like it does. See #1057 and #1011. I'll close this as a duplicate of those for now. Thanks for reporting.

**Closed** 2020-09-17 06:03 UTC
Labels: duplicate
