### ISSUE TITLE
pyqtgraph doesnt work with pyqt5 on macos 

### ISSUE THREAD

**Issue by pzoltowski** [pyqtgraph/pyqtgraph#488] opened 2017-05-27 07:13 UTC
I had a working pyqtgraph on my macbook (sierra) before but had to migrate to pyqt5. I cannot make it work again.  I have Qt5 (_5.8.0_2_) and PyQt5 (5.8.2) both installed using homebrew. I'm using python 2.7 (2.7.13). I tried reinstalling pyqtgraph-0.10 using pip, then manually and even from develop github branch and still without luck.

I used the tip to add the following before importing pyqtgraph:
```
import os
os.environ['PYQTGRAPH_QT_LIB'] = 'PyQt5'
```

each time I get:
```
>>> import os
>>> os.environ['PYQTGRAPH_QT_LIB'] = 'PyQt5'
>>> import pyqtgraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyqtgraph/__init__.py", line 30, in <module>
    from . import python2_3
ImportError: cannot import name python2_3
```
the following works fine in my setup:

```
from PyQt5.QtCore import *
from PyQt5.QtGui import *
```

**Comment by ausk** [comment] 2017-06-21 13:34
On my Ubuntu 16.04.02 + Python3.5 + PyQt5.8.2, it works almost fine. Today, after fixing some compatibality issues, all the examples except  "CheckTable" and "VerticalLabel" in Widgets can work perfectly.
That is to say, it is not the software's issues, maybe you just didn't install the pyqtgraph properly, or the path may be wrong. You can just check the install path, to make sure that the python2_3.py exists.

```
pyqtgraph
./__init__.py
./python2_3.py
./Qt.py 
./...
```

Best wish!

**Comment by j9ac9k** [comment] 2019-06-07 22:13
Going to close this out as we can't reproduce; and there have been a significant number of code changes since this issue was made.

**Closed by j9ac9k** 2019-06-07 22:13 UTC
