### ISSUE TITLE
Bug in TableWidget.py

### ISSUE THREAD

**Issue by choogeGL** [pyqtgraph/pyqtgraph#1128] opened 2020-02-14 00:05 UTC
### Short description
I believe there is a bug in Line 8 of the widgets/TableWidget.py file where it is currently:

__all__ = ['TableWidget']

when the line should be:
__all__ = ['TableWidget','TableWidgetItem']

### Real behavior

```
AttributeError: type object 'TableWidget' has no attribute 'TableWidgetItem'
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0.dev0+g6a2791e

**Comment by ixjlyons** [comment] 2020-03-07 18:04
Duplicate of #1115

**Closed by ixjlyons** 2020-03-07 18:04 UTC
