### ISSUE TITLE
Unable to save flowchart in flowchart GUI

### ISSUE THREAD

**Issue by hzyrc6011** [pyqtgraph/pyqtgraph#1196] opened 2020-05-10 02:19 UTC
### Short description

When clicking the "save" button to save flowcharts, It throws an exception,like this.
```
fileName = unicode(fileName)
NameError: name 'unicode' is not defined
```
and the GUI collapse unexpectedly.

### Code to reproduce

The code is right the example of "flowchart" in pyqtgraph.examples.

```python
# -*- coding: utf-8 -*-
"""
This example demonstrates a very basic use of flowcharts: filter data,
displaying both the input and output of the filter. The behavior of
the filter can be reprogrammed by the user.

Basic steps are:
  - create a flowchart and two plots
  - input noisy data to the flowchart
  - flowchart connects data to the first plot, where it is displayed
  - add a gaussian filter to lowpass the data, then display it in the second plot.
"""
import initExample ## Add path to library (just for examples; you do not need this)


from pyqtgraph.flowchart import Flowchart
from pyqtgraph.Qt import QtGui, QtCore
import pyqtgraph as pg
import numpy as np
import pyqtgraph.metaarray as metaarray

app = QtGui.QApplication([])

## Create main window with grid layout
win = QtGui.QMainWindow()
win.setWindowTitle('pyqtgraph example: Flowchart')
cw = QtGui.QWidget()
win.setCentralWidget(cw)
layout = QtGui.QGridLayout()
cw.setLayout(layout)

## Create flowchart, define input/output terminals
fc = Flowchart(terminals={
    'dataIn': {'io': 'in'},
    'dataOut': {'io': 'out'}    
})
w = fc.widget()

## Add flowchart control panel to the main window
layout.addWidget(fc.widget(), 0, 0, 2, 1)

## Add two plot widgets
pw1 = pg.PlotWidget()
pw2 = pg.PlotWidget()
layout.addWidget(pw1, 0, 1)
layout.addWidget(pw2, 1, 1)

win.show()

## generate signal data to pass through the flowchart
data = np.random.normal(size=1000)
data[200:300] += 1
data += np.sin(np.linspace(0, 100, 1000))
data = metaarray.MetaArray(data, info=[{'name': 'Time', 'values': np.linspace(0, 1.0, len(data))}, {}])

## Feed data into the input terminal of the flowchart
fc.setInput(dataIn=data)

## populate the flowchart with a basic set of processing nodes. 
## (usually we let the user do this)
plotList = {'Top Plot': pw1, 'Bottom Plot': pw2}

pw1Node = fc.createNode('PlotWidget', pos=(0, -150))
pw1Node.setPlotList(plotList)
pw1Node.setPlot(pw1)

pw2Node = fc.createNode('PlotWidget', pos=(150, -150))
pw2Node.setPlot(pw2)
pw2Node.setPlotList(plotList)

fNode = fc.createNode('GaussianFilter', pos=(0, 0))
fNode.ctrls['sigma'].setValue(5)
fc.connectTerminals(fc['dataIn'], fNode['In'])
fc.connectTerminals(fc['dataIn'], pw1Node['In'])
fc.connectTerminals(fNode['Out'], pw2Node['In'])
fc.connectTerminals(fNode['Out'], fc['dataOut'])



## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()

```

### Expected behavior

save the ".fc" file
### Real behavior

```
/home/hzy/anaconda3/envs/femcalc/lib/python3.6/site-packages/pyqtgraph/functions.py:1276: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  filtered = filtered[sl]
Traceback (most recent call last):
  File "/home/hzy/anaconda3/envs/femcalc/lib/python3.6/site-packages/pyqtgraph/flowchart/Flowchart.py", line 538, in saveFile
    fileName = unicode(fileName)
NameError: name 'unicode' is not defined
Fatal Python error: Aborted

Current thread 0x00007f517801c700 (most recent call first):
  File "<stdin>", line 84 in <module>
```

### Tested environment(s)

 * PyQtGraph version: '0.10.0'
 * Qt Python binding: 'PyQt5 5.12.3 Qt 5.12.5'
 * Python version: Python 3.6.7
 * NumPy version: 1.17.5 
 * Operating system: deepin linux 15.11(acts like ubuntu 16.04)
 * Installation method:pip install pyqtgraph

**Comment by ixjlyons** [comment] 2020-05-10 04:28
Thanks for the detailed report. This is a duplicate of #512 and was fixed with #886. You can get the 0.11.0 release candidate with `pip install pyqtgraph==0.11.0rc0`. You could also install the latest with `pip install git+https://github.com/pyqtgraph/pyqtgraph@develop`.

**Closed by ixjlyons** 2020-05-10 04:28 UTC
