### ISSUE TITLE
 Error sending hover exit event

### ISSUE THREAD

**Issue by 3fon3fonov** [pyqtgraph/pyqtgraph#1499] opened 2021-01-17 10:20 UTC
Hi All, 

since I updated to pyqtgraph ver. 0.11, from time to time I am getting the following error:

[11:15:48]  Error sending hover exit event:

    |==============================>>
    |  Traceback (most recent call last):
    |    File "exostriker_gui.py", line 3, in <module>
    |      exostriker.gui.main()
    |    File "/home/trifonov/git/exostriker-ready/exostriker/gui.py", line 9473, in main
    |      sys.exit(app.exec_())
    |    File "/home/trifonov/git/exostriker-ready/exostriker/lib/pyqtgraph/widgets/GraphicsView.py", line 382, in mouseMoveEvent
    |      QtGui.QGraphicsView.mouseMoveEvent(self, ev)
    |    File "/home/trifonov/git/exostriker-ready/exostriker/lib/pyqtgraph/GraphicsScene/GraphicsScene.py", line 202, in mouseMoveEvent
    |      self.sendHoverEvents(ev)
    |    File "/home/trifonov/git/exostriker-ready/exostriker/lib/pyqtgraph/GraphicsScene/GraphicsScene.py", line 304, in sendHoverEvents
    |      debug.printExc("Error sending hover exit event:")
    |    --- exception caught here ---
    |    File "/home/trifonov/git/exostriker-ready/exostriker/lib/pyqtgraph/GraphicsScene/GraphicsScene.py", line 301, in sendHoverEvents
    |      if item.scene() is self:
    |  RuntimeError: wrapped C/C++ object of type ScatterPlotItem has been deleted
    |==============================<<

So far, I cannot reproduce the error. It seems that apears somewhat randomly.
Any ideas?

**Comment by pijyoi** [comment] 2021-01-17 10:51
While running with PySide6, it was always triggered with the verlet_chain_demo.py but not when running with PySide2 and PyQt5.
https://github.com/pyqtgraph/pyqtgraph/pull/1495/commits/74683be68b8411e10e64b87341508370ce4bbf3c

So it looks like this is not PySide6 specific.

**Comment by dglent** [comment] 2021-01-18 07:16
I had the same error after updating to 0.11.1
I use multiple Viewboxes to have multiple Y axis
I have a button to switch from PlotCurveItem to PlotDataItem curve in order to show the points of the curve.
To switch curve, i created every time a new PlotDataItem curve (and to go back i created every time a new PlotCurveItem)
After switching from PlotCurveItem to PlotDataItem, if the mouse was over the graphic area and after moving the mouse, i had your error message.
To solve this, i created two curves (one PlotCurveItem, one PlotDataItem) and i store them in a list. Then to switch them i used viewbox.addItem / viewbox.removeItem

**Comment by 3fon3fonov** [comment] 2021-01-20 09:06
Thnaks @dglent! I think the problem is indeed in the mouse pointer! I was able to reproduce the bug when the plot has changed while the mouse is on the plot! I have not tried your sollution because that whould mean that I must re-write quite some code, and I do not really want to make my life complicated. Since this bug was not evident in pyqtgraph v 0.10, I think there must be a more general solution within the new version 0.11. So I will trust the developers to fix it.

**Comment by BenStrowbridge** [comment] 2022-05-17 21:03
Just wondering if anyone found where the change that created this problem was and how to deal with it? I had exactly the same problem going from version 0.10 to 0.11 with notices in the hover exit event about both plotItem and infinteLine being deleted. I've dealt with this by installing version 0.10 on new computers but wondering if a fix is possible? If not, can we keep the mac and PC binary installers for version 0.10 available over the long term?

**Comment by j9ac9k** [comment] 2022-05-17 21:12
> If not, can we keep the mac and PC binary installers for version 0.10 available over the long term?

I mean you could, I believe 0.10 worked with PyQt5 5.12, so as long as you can run that, you should be ok; but there are hundreds of serious bug-fixes that have come since 0.10.  

@BenStrowbridge If you have a reproducible example of the issue, I can try and debug further, but I haven't seen this error in quite some time myself.

**Comment by pijyoi** [comment] 2022-05-17 21:16
0.11.x is quite old. Are you not able to use 0.12.4?

Does the change in the following commit help you?  https://github.com/pyqtgraph/pyqtgraph/pull/1495/commits/74683be68b8411e10e64b87341508370ce4bbf3c

**Comment by BenStrowbridge** [comment] 2022-05-17 21:33
Thanks for the responses. I use the standard Anaconda download which has version 5.9.7 of Qt. I got an error message trying to install newer versions of pyqtgraph that 0.12.4 requires Qt > 5.12. I can run both 0.11.0 and 0.11.1 with the standard anaconda system and they both give the error message while 0.10.0 does not. The module that has the error message is part of a suite of programs. I will try to make a standalone program tomorrow that provide via email.

**Comment by j9ac9k** [comment] 2022-05-17 21:41
> Thanks for the responses. I use the standard Anaconda download which has version 5.9.7 of Qt. I got an error message trying to install newer versions of pyqtgraph that 0.12.4 requires Qt > 5.12. I can run both 0.11.0 and 0.11.1 with the standard anaconda system and they both give the error message while 0.10.0 does not. The module that has the error message is part of a suite of programs. I will try to make a standalone program tomorrow to provide via email.

If you're wanting to use conda distributions of Qt bindings, you'll need to use either the PyQt5 (Qt 5.15) or PySide2 (Qt 5.12) bindings on `conda-forge`.  If you can't use the bindings on conda forge, and can't install bindings from PyPi via pip, than you will need to stick to old versions of pyqtgraph.

**Comment by BenStrowbridge** [comment] 2022-05-17 21:52
Thanks so much. I got 0.12.4 going by loading PyQt5 via pip, as you suggested, and the hover error message is gone. So it must have been fixed sometime after 0.11.1. Now getting some depreciation messages but I should be able to handle those. Thanks.

**Comment by j9ac9k** [comment] 2022-10-01 04:44
Looks like this issue has been fixed so I'm going to close this out 👍🏻

**Closed by j9ac9k** 2022-10-01 04:44 UTC
