### ISSUE TITLE
TypeError:native Qt signal is not callable in GraphicsObject

### ISSUE THREAD

**Issue by NeanderThaler** [pyqtgraph/pyqtgraph#2152] opened 2021-12-14 07:51 UTC
TypeError:native Qt signal is not callable

in GrapicsObject.py:24

    def itemChange(self, change, value):
        ret = super().itemChange(change, value)
        if change in [self.GraphicsItemChange.ItemParentHasChanged, self.GraphicsItemChange.ItemSceneHasChanged]:
            self.parentChanged()

### Short description
see above

### Code to reproduce
```python
 self.view = pg.GraphicsView()
        self.l = pg.GraphicsLayout()
        self.view.setCentralItem(self.l)
        self.view.show()
        self.plotitem = self.l.addPlot(0, 0)
```

### Expected behavior
No exception

### Real behavior
An exception

### Tested environment(s)
* PySide6

**Comment by edwinsnow** [comment] 2021-12-14 14:16
The issue has apparently appeared with updating python to 3.10 and PySide6 to 6.2.2.  It seems that PySide6 has now reserved 'parentChanged' for one of its signals and it now conflicts with pyqtgraph's function name.  Hotfixed it with running Find and Replace from 'parentChanged' to 'parentChanged1' over the local pyqtgraph installation directory, do not know whether it leads to any side effects.  As the issue is pretty critical and probably easy to fix, it would be nice to have a guidance towards the timeline of its resolution, if possible.

**Comment by NeanderThaler** [comment] 2021-12-14 19:59
For the record: I'm working with Python 3.7 and with the latest PySide6 6.2.2.1. 
I worked around it, by changing the line to 'self.parentChanged.emit()'  but based on your explanation, i guess that this isn't a good fix, but renaming the function would be the better way. Thanks.

**Comment by j9ac9k** [comment] 2021-12-14 22:34
The fix has been merged in master already and will be incorporated into the next release, see #2132 

This issue was also reported (and fixed) upstream as well: https://bugreports.qt.io/browse/PYSIDE-1730

**Closed by j9ac9k** 2021-12-14 22:34 UTC
