### ISSUE TITLE
3D Graphics is not work.  pyqtgraph.opengl not work.

### ISSUE THREAD

**Issue by zhoubo-lab** [pyqtgraph/pyqtgraph#1075] opened 2019-11-12 06:39 UTC
The issue report as the following show and my pyqtgraph version is 0.11.0.dev0

  File "C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 14, in <module>
    w = gl.GLViewWidget()

AttributeError: module 'pyqtgraph.opengl' has no attribute 'GLViewWidget'

**Comment by zhoubo-lab** [comment] 2019-11-12 08:02
1: I doubt it is OpenGL.GL issue. Because I try to link this OpenGL.GL, But it can not open. But when I try to download this file, there is no right version which can be found by myself. 
2:  Above information just some clue for you.

from OpenGL.GL import *
from OpenGL import GL

**Comment by zhoubo-lab** [comment] 2019-11-14 01:32
It is not OpenGL.GL issue because I install it, but it still not work. 
S

**Comment by ixjlyons** [comment] 2019-11-14 04:17
A few questions that might help figure out what's going on:

- What exactly are you trying to run? Could you provide a script that gives this error?
- How did you install pyqtgraph?
- Could you share the output of `conda list`?

**Comment by zhoubo-lab** [comment] 2019-11-14 04:45
the following is my script which is demo of example: 
# -*- coding: utf-8 -*-
"""
Demonstrates GLVolumeItem for displaying volumetric data.
"""
## Add path to library (just for examples; you do not need this)
#import initExample

from PyQt5 import QtGui
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtGui
import pyqtgraph.opengl as gl

app = QtGui.QApplication([])
w = gl.GLViewWidget()
w.opts['distance'] = 200
w.show()
w.setWindowTitle('pyqtgraph example: GLVolumeItem')

#b = gl.GLBoxItem()
#w.addItem(b)
g = gl.GLGridItem()
g.scale(10, 10, 1)
w.addItem(g)

import numpy as np
## Hydrogen electron probability density
def psi(i, j, k, offset=(50,50,100)):
    x = i-offset[0]
    y = j-offset[1]
    z = k-offset[2]
    th = np.arctan2(z, (x**2+y**2)**0.5)
    phi = np.arctan2(y, x)
    r = (x**2 + y**2 + z **2)**0.5
    a0 = 2
    #ps = (1./81.) * (2./np.pi)**0.5 * (1./a0)**(3/2) * (6 - r/a0) * (r/a0) * np.exp(-r/(3*a0)) * np.cos(th)
    ps = (1./81.) * 1./(6.*np.pi)**0.5 * (1./a0)**(3/2) * (r/a0)**2 * np.exp(-r/(3*a0)) * (3 * np.cos(th)**2 - 1)
    
    return ps
    
    #return ((1./81.) * (1./np.pi)**0.5 * (1./a0)**(3/2) * (r/a0)**2 * (r/a0) * np.exp(-r/(3*a0)) * np.sin(th) * np.cos(th) * np.exp(2 * 1j * phi))**2 


data = np.fromfunction(psi, (100,100,200))
positive = np.log(np.clip(data, 0, data.max())**2)
negative = np.log(np.clip(-data, 0, -data.min())**2)

d2 = np.empty(data.shape + (4,), dtype=np.ubyte)
d2[..., 0] = positive * (255./positive.max())
d2[..., 1] = negative * (255./negative.max())
d2[..., 2] = d2[...,1]
d2[..., 3] = d2[..., 0]*0.3 + d2[..., 1]*0.3
d2[..., 3] = (d2[..., 3].astype(float) / 255.) **2 * 255

d2[:, 0, 0] = [255,0,0,100]
d2[0, :, 0] = [0,255,0,100]
d2[0, 0, :] = [0,0,255,100]

v = gl.GLVolumeItem(d2)
v.translate(-50,-50,-100)
w.addItem(v)

ax = gl.GLAxisItem()
w.addItem(ax)

## Start Qt event loop unless running in interactive mode.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()

**Comment by zhoubo-lab** [comment] 2019-11-14 04:45
Here is error:  
 w = gl.GLViewWidget()

AttributeError: module 'pyqtgraph.opengl' has no attribute 'GLViewWidget'

**Comment by zhoubo-lab** [comment] 2019-11-14 04:47
Here is conda list
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
alabaster                 0.7.12                   py37_0    defaults
anaconda                  2019.07                  py37_0    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.7                    py37_0    defaults
anaconda-project          0.8.3                      py_0    defaults
asammdf                   5.13.11.dev0             pypi_0    pypi
asn1crypto                0.24.0                   py37_0    defaults
astroid                   2.2.5                    py37_0    defaults
astropy                   3.2.1            py37he774522_0    defaults
atomicwrites              1.3.0                    py37_1    defaults
attrs                     19.1.0                   py37_1    defaults
babel                     2.7.0                      py_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.5                        py_2    defaults
backports.os              0.1.1                    py37_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.7.1                    py37_1    defaults
bitarray                  0.9.3            py37he774522_0    defaults
bitstruct                 8.8.1                    pypi_0    pypi
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
blosc                     1.16.3               h7bd577a_0    defaults
bokeh                     1.2.0                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.2.1            py37h452e1ab_1    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2019.5.15                     0    defaults
canmatrix                 0.8                      pypi_0    pypi
cchardet                  2.1.4                    pypi_0    pypi
certifi                   2019.6.16                py37_0    defaults
cffi                      1.12.3           py37h7a1dbc1_0    defaults
chardet                   3.0.4                    py37_1    defaults
click                     7.0                      py37_0    defaults
cloudpickle               1.2.1                      py_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
comtypes                  1.1.7                    py37_0    defaults
conda                     4.7.10                   py37_0    defaults
conda-build               3.18.8                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.3.11                   py37_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         3    defaults
contextlib2               0.5.5                    py37_0    defaults
cryptography              2.7              py37h7a1dbc1_0    defaults
curl                      7.65.2               h2a8f88b_0    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.12          py37ha925a31_0    defaults
cytoolz                   0.10.0           py37he774522_0    defaults
dask                      2.1.0                      py_0    defaults
dask-core                 2.1.0                      py_0    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.6.0                      py_0    defaults
distributed               2.1.0                      py_0    defaults
docutils                  0.14                     py37_0    defaults
entrypoints               0.3                      py37_0    defaults
et_xmlfile                1.0.1                    py37_0    defaults
fastcache                 1.1.0            py37he774522_0    defaults
filelock                  3.0.12                     py_0    defaults
flask                     1.1.1                      py_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
future                    0.17.1                   py37_0    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.4.0            py37he774522_0    defaults
glob2                     0.7                        py_0    defaults
greenlet                  0.4.15           py37hfa6e2cd_0    defaults
h5py                      2.9.0            py37h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
heapdict                  1.0.0                    py37_2    defaults
html5lib                  1.0.1                    py37_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.8                      py37_0    defaults
imageio                   2.5.0                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
importlib_metadata        0.17                     py37_1    defaults
intel-openmp              2019.4                      245    defaults
ipykernel                 5.1.1            py37h39e3cac_0    defaults
ipython                   7.6.1            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.5.0                      py_0    defaults
isort                     4.3.21                   py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.13.3                   py37_0    defaults
jinja2                    2.10.1                   py37_0    defaults
joblib                    0.13.2                   py37_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
json5                     0.8.4                      py_0    defaults
jsonschema                3.0.1                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.3.1                      py_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.5.0                      py_0    defaults
jupyterlab                1.0.2            py37hf63ae98_0    defaults
jupyterlab_server         1.0.0                      py_0    defaults
keyring                   18.0.0                   py37_0    defaults
kiwisolver                1.1.0            py37ha925a31_0    defaults
krb5                      1.16.1               hc04afaa_7    defaults
lazy-object-proxy         1.4.1            py37he774522_0    defaults
libarchive                3.3.3                h0643e63_5    defaults
libcurl                   7.65.2               h2a8f88b_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
liblief                   0.9.0                ha925a31_2    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libssh2                   1.8.2                h7a1dbc1_0    defaults
libtiff                   4.0.10               hb898794_2    defaults
libxml2                   2.9.9                h464c3ec_0    defaults
libxslt                   1.1.33               h579f668_0    defaults
llvmlite                  0.29.0           py37ha925a31_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.3.4            py37h1350720_0    defaults
lz4-c                     1.8.1.2              h2fa13f4_0    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.1.1            py37he774522_0    defaults
matplotlib                3.1.0            py37hc8f65d3_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mdfreader                 3.2                      pypi_0    pypi
menuinst                  1.4.16           py37he774522_0    defaults
mistune                   0.8.4            py37he774522_0    defaults
mkl                       2019.4                      245    defaults
mkl-service               2.0.2            py37he774522_0    defaults
mkl_fft                   1.0.12           py37h14836fe_0    defaults
mkl_random                1.0.2            py37h343c172_0    defaults
mock                      3.0.5                    py37_0    defaults
more-itertools            7.0.0                    py37_0    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            0.6.1            py37h74a9793_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.6.0                    py37_0    defaults
natsort                   6.0.0                    pypi_0    pypi
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.5.0                      py_0    defaults
nbformat                  4.4.0                    py37_0    defaults
networkx                  2.3                        py_0    defaults
nltk                      3.4.4                    py37_0    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  6.0.0                    py37_0    defaults
numba                     0.44.1           py37hf9181ef_0    defaults
numexpr                   2.6.9            py37hdce8814_0    defaults
numpy                     1.16.4           py37h19fb1c0_0    defaults
numpy-base                1.16.4           py37hc3f5095_0    defaults
numpydoc                  0.9.1                      py_0    defaults
olefile                   0.46                     py37_0    defaults
opengl-registry           0.1.0                    pypi_0    pypi
openpyxl                  2.6.2                      py_0    defaults
openssl                   1.1.1c               he774522_1    defaults
packaging                 19.0                     py37_0    defaults
pandas                    0.24.2           py37ha925a31_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.5.0                      py_0    defaults
partd                     1.0.0                      py_0    defaults
path.py                   12.0.1                     py_0    defaults
pathlib2                  2.3.4                    py37_0    defaults
patsy                     0.5.1                    py37_0    defaults
pep8                      1.7.1                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    6.1.0            py37hdc69c19_0    defaults
pip                       19.2.3                   pypi_0    pypi
pkginfo                   1.5.0.1                  py37_0    defaults
pluggy                    0.12.0                     py_0    defaults
ply                       3.11                     py37_0    defaults
powershell_shortcut       0.0.1                         2    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
psutil                    5.6.3            py37he774522_0    defaults
py                        1.8.0                    py37_0    defaults
py-lief                   0.9.0            py37ha925a31_2    defaults
pycodestyle               2.5.0                    py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1            py37hfa6e2cd_9    defaults
pycurl                    7.43.0.3         py37h7a1dbc1_0    defaults
pyflakes                  2.1.1                    py37_0    defaults
pygments                  2.4.2                      py_0    defaults
pylint                    2.3.1                    py37_0    defaults
pyodbc                    4.0.26           py37ha925a31_0    defaults
pyopengl                  3.1.0                    pypi_0    pypi
pyopenglng                0.1.2                    pypi_0    pypi
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.4.0                      py_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
pyqtgraph                 0.11.0.dev0              pypi_0    pypi
pyreadline                2.1                      py37_1    defaults
pyrsistent                0.14.11          py37he774522_0    defaults
pyside2                   5.13.2                   pypi_0    pypi
pysocks                   1.7.0                    py37_0    defaults
pytables                  3.5.2            py37h1da0976_1    defaults
pytest                    5.0.1                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.5.0                    py37_0    defaults
pytest-doctestplus        0.3.0                    py37_0    defaults
pytest-openfiles          0.3.2                    py37_0    defaults
pytest-remotedata         0.3.1                    py37_0    defaults
python                    3.7.3                h8c8aaf0_1    defaults
python-dateutil           2.8.0                    py37_0    defaults
python-libarchive-c       2.8                     py37_11    defaults
pytz                      2019.1                     py_0    defaults
pywavelets                1.0.3            py37h8c2d366_1    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
pywinpty                  0.5.5                 py37_1000    defaults
pyyaml                    5.1.1            py37he774522_0    defaults
pyzmq                     18.0.0           py37ha925a31_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 0.5.7                    py37_1    defaults
qtconsole                 4.5.1                      py_0    defaults
qtpy                      1.8.0                      py_0    defaults
requests                  2.22.0                   py37_0    defaults
rope                      0.14.0                     py_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
scikit-image              0.15.0           py37ha925a31_0    defaults
scikit-learn              0.21.2           py37h6288b17_0    defaults
scipy                     1.2.1            py37h29ff71c_0    defaults
seaborn                   0.9.0                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                41.2.0                   pypi_0    pypi
shiboken2                 5.13.2                   pypi_0    pypi
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.12.0                   py37_0    defaults
snappy                    1.1.7                h777316e_3    defaults
snowballstemmer           1.9.0                      py_0    defaults
sortedcollections         1.1.2                    py37_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
soupsieve                 1.8                      py37_0    defaults
speech                    0.5.2                    pypi_0    pypi
sphinx                    2.1.2                      py_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-applehelp   1.0.1                      py_0    defaults
sphinxcontrib-devhelp     1.0.1                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.2                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.2                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.3                      py_0    defaults
sphinxcontrib-websupport  1.1.2                      py_0    defaults
spyder                    3.3.6                    py37_0    defaults
spyder-kernels            0.5.1                    py37_0    defaults
sqlalchemy                1.3.5            py37he774522_0    defaults
sqlite                    3.29.0               he774522_0    defaults
statsmodels               0.10.0           py37h8c2d366_0    defaults
sympy                     1.4                      py37_0    defaults
tblib                     1.4.0                      py_0    defaults
terminado                 0.8.2                    py37_0    defaults
testpath                  0.4.2                    py37_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
toolz                     0.10.0                     py_0    defaults
tornado                   6.0.3            py37he774522_0    defaults
tqdm                      4.32.1                     py_0    defaults
traitlets                 4.3.2                    py37_0    defaults
unicodecsv                0.14.1                   py37_0    defaults
urllib3                   1.24.2                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
veusz                     3.0.1                    pypi_0    pypi
vs2015_runtime            14.15.26706          h3a45250_4    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.15.4                     py_0    defaults
wheel                     0.33.4                   py37_0    defaults
widgetsnbextension        3.5.0                    py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
win_unicode_console       0.5                      py37_0    defaults
wincertstore              0.2                      py37_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.11.2           py37he774522_0    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.1.8                      py_0    defaults
xlwings                   0.15.8                   py37_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.3.1                h33f27b4_3    defaults
zict                      1.0.0                      py_0    defaults
zipp                      0.5.1                      py_0    defaults
zlib                      1.2.11               h62dcd97_3    defaults
zstd                      1.3.7                h508b16e_0    defaults

**Comment by ixjlyons** [comment] 2019-11-20 04:46
I would suggest trying to re-install pyqtgraph maybe. Again, how did you install 0.11.0.dev in the first place? Aside from that, I guess we need some more information about your environment. Are you using an IDE? Or how are you executing the example script?

**Comment by zhoubo-lab** [comment] 2019-11-20 08:33
Hi thanks for your feedback
A:) I install 0.11.0.dev is because one of whl need this version to run.
B:) The information of your need: 
B.1):  Environment
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.

B.2): IDE: Spyder (anaconda3)
I use this IDE to run script

C:) In addtion infomation : All 2D scripts work well, only 3D scripts not work.

**Comment by j9ac9k** [comment] 2019-11-25 15:35
hi @zhoubo-lab 

I'm still curious how you installed pyqtgraph, you're not getting the git commit hash as part of the dev version, which is a bit puzzling.  Also it appears you have a whole lot of packages installed to that python environment; it's possible that there is some conflict with pyopengl.

Alternatively, if you want us to reproduce, can you provide us with an `environment.yml` file and i'll try and recreate the same environment you're using.

Also instead of running the script with spyder, can you just try and run from the terminal via `python your_script.py`.

I'm going to label the issue can't reproduce for the time being.

**Comment by zhoubo-lab** [comment] 2019-11-26 01:26
There are three folder which have environment.yml file.
1: In folder: C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\pkgs\conda-4.7.10-py37_0\info\test\tests\conda_env\support\saved-env. The content as following show:

name: to-save
dependencies:
  - python

**Comment by zhoubo-lab** [comment] 2019-11-26 01:27
2: In folder: C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\pkgs\conda-4.7.10-py37_0\info\test\tests\conda_env\support\foo: the content as the following show:

name: test
dependencies:
  - numpy

**Comment by zhoubo-lab** [comment] 2019-11-26 01:29
3: In folder: C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\pkgs\conda-4.7.10-py37_0\info\test\tests\conda_env\support\example: the contetn of environment.yml as the folloing show: 
name: test
dependencies:
  - numpy

**Comment by zhoubo-lab** [comment] 2019-11-26 01:32
In the 3 folder: C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\pkgs\conda-4.7.10-py37_0\info\test\tests\conda_env\support\example.  there are another two files: 
A: environment_pinned.yml
B: environment_pinned_updated.yml
A: environment_pinned.yml 's content: 
name: test
dependencies:
  - flask==0.12.2


B:  environment_pinned_updated.yml's content: 
name: test
dependencies:
  - flask==1.0.2

Hope those information can be helpful.

**Comment by zhoubo-lab** [comment] 2019-11-26 01:32
In the 3 folder: C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\pkgs\conda-4.7.10-py37_0\info\test\tests\conda_env\support\example.  there are another two files: 
A: environment_pinned.yml
B: environment_pinned_updated.yml
A: environment_pinned.yml 's content: 
name: test
dependencies:
  - flask==0.12.2


B:  environment_pinned_updated.yml's content: 
name: test
dependencies:
  - flask==1.0.2

Hope those information can be helpful.

**Comment by zhoubo-lab** [comment] 2019-11-26 01:43
And I use python to run, the following is results:

C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\Lib\site-packages\pyqtgraph\examples>python GLVolumeItem.py
Using PyQt5 (default graphics system)
Traceback (most recent call last):
  File "GLVolumeItem.py", line 11, in <module>
    import pyqtgraph.opengl as gl
  File "C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyqtgraph\opengl\__init__.py", line 1, in <module>
    from .GLViewWidget import GLViewWidget
  File "C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\lib\site-packages\pyqtgraph\opengl\GLViewWidget.py", line 14, in <module>
    w = gl.GLViewWidget()
AttributeError: module 'pyqtgraph.opengl' has no attribute 'GLViewWidget'

C:\Users\zhoubo\AppData\Local\Continuum\anaconda3\Lib\site-packages\pyqtgraph\examples>

**Comment by j9ac9k** [comment] 2019-11-26 02:13
Can you tell us how you installed pyqtgraph?

**Comment by zhoubo-lab** [comment] 2019-12-01 09:24
Dear: 
A):  Thanks very much for your reply.  the following is information of my way about install on another my computer. The 3D part of running example also still not work as before. but All other part of running example work well.
B):  Consultation：What is correct way of install pyqtgraph? 


pip install pyqtgraph
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pyqtgraph
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/cd/ad/307e0280df5c19986c4206d138ec3a8954afc722cea991f4adb4a16337d9/pyqtgraph-0.10.0.tar.gz
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from pyqtgraph) (1.17.3)
Building wheels for collected packages: pyqtgraph
  Building wheel for pyqtgraph (setup.py) ... done
  Created wheel for pyqtgraph: filename=pyqtgraph-0.10.0-cp37-none-any.whl size=734820 sha256=97dca5ad8e1088f4a516dbe5cd9de8ecdd7a09c75b7b7a9fccf57a43881c90ef
  Stored in directory: C:\Users\Administrator\AppData\Local\pip\Cache\wheels\11\de\ff\c633a34fcd705578cf09555cce1437e64af0489f83164bdf86
Successfully built pyqtgraph
Installing collected packages: pyqtgraph
Successfully installed pyqtgraph-0.10.0

**Comment by j9ac9k** [comment] 2020-03-10 17:10
Hi @zhoubo-lab sorry for the slow response, just realized I didn't reply.

I would suggest creating a new python environment

```bash
python3 -m venv .venv
source .venv/bin/activate
```

From there, install the Qt bindings of your choice as well as the dependencies

```bash
pip install PyQt5 numpy scipy pyopengl pyqtgraph==0.11rc0
```

(we have release candidate 0 available on pypi right now, which is what we recommend people install, as 0.11 will be released shortly)

From this point on, you should be able to run the examples

```bash
python -m pyqtgraph.examples
```

I'm going to close out this issue, but if you're still having problems, let us know and I'll re-open.

**Closed by j9ac9k** 2020-03-10 17:10 UTC
Labels: cannot reproduce
