### ISSUE TITLE
Pen line style changes depending on data Range

### ISSUE THREAD

**Issue by filippeof** [pyqtgraph/pyqtgraph#2354] opened 2022-07-07 16:06 UTC
### Short description

When using a qt style (e.g. dashed line) for  a pen, the line style changes to a solid line with some transparency. A modified version of the Plot auto-range example should reproduce the error.

### Code to reproduce

```python
import time

import numpy as np

import pyqtgraph as pg
from pyqtgraph.Qt import QtCore

app = pg.mkQApp("Plot Auto Range Example")

win = pg.GraphicsLayoutWidget(show=True, title="Plot auto-range examples")
win.resize(800,600)
win.setWindowTitle('pyqtgraph example: PlotAutoRange')

d = np.random.normal(size=100)
d[50:54] += 10
p1 = win.addPlot(title="95th percentile range", y=d,pen=pg.mkPen(color=(29, 161, 242), style=QtCore.Qt.DashLine, width=3))
p1.enableAutoRange('y', 0.95)


p2 = win.addPlot(title="Auto Pan Only")
p2.setAutoPan(y=True)
curve= p2.plot(pen=pg.mkPen(color=(29, 161, 242), style=QtCore.Qt.DashLine, width=3))

t0 = time.time()

def update():
    t = time.time() - t0
    
    data = np.ones(100) * np.sin(t)
    data[50:60] += np.sin(t)
    curve.setData(data)
    
timer = QtCore.QTimer()
timer.timeout.connect(update)
timer.start(50)

if __name__ == '__main__':
    pg.exec()
```

### Expected behavior

line style should correspond to defined one
### Real behavior

line style changes depending on range/zoom

```
no error msg
```

### Tested environment(s)

 * PyQtGraph version: 0.12.4 
 * Qt Python binding: PyQt5 5.15.6 Qt 5.15.2 
 * Python version: 3.10.5
 * NumPy version:1.22.3 
 * Operating system: linux, fc35.x86_64
 * Installation method: pip

**Comment by pijyoi** [comment] 2022-07-29 12:06
I am not able to reproduce your described behavior. On both the left-hand and right-hand side plots, I see a blue dashed line plot. (0.12.4 or master, Windows)

**Comment by filippeof** [comment] 2022-07-29 13:23
Thanks for taking a look at that @pijyoi,
I confirm that on windows everything looks fine. It appears to be a linux issue only (see gif below). I am happy to provide more information to narrow down the issue.
![cinnamon-20220729-4](https://user-images.githubusercontent.com/11142094/181769183-fd32c4f5-e7d4-4f10-b5d0-4a45930d02c7.gif)

**Comment by pijyoi** [comment] 2022-07-29 13:56
I tried it out on Ubuntu 20.04 and can't reproduce it there either. I tried switching on/off wayland, fractional scaling, but it still works fine.

**Comment by pijyoi** [comment] 2022-07-30 10:33
Could you try setting the pen width to something thicker? It seems to me that the pen width is also being reset to 1, but it's not so obvious with pen width=3 in your animated gif.

**Comment by filippeof** [comment] 2022-08-09 10:41
Thank you for your answer, @pijyoi.
I tried with a wider line (10) and it seems that the width is kept.
![cinnamon-20220809-7](https://user-images.githubusercontent.com/11142094/183628773-27447dee-2108-462c-8bc2-bb9e147f2ea6.gif)

**Comment by j9ac9k** [comment] 2022-10-01 04:12
This one is going to be tricky for us to attempt to reproduce.  The only thing I can suggest is to try and switch to a different Qt binding and see if you have the issue continues occurring.

**Comment by ixjlyons** [comment] 2022-10-02 16:47
I have a fairly similar environment (OpenSUSE Tumbleweed, python 3.10.7, PyQt5 5.16.6, Qt 5.15.2), and I haven't been able to reproduce this issue.

What desktop environment are you using? Is it Wayland based? I'm not sure if that matters, just a hunch. Seems like a Qt issue in any case.

**Comment by campagnola** [comment] 2022-10-02 17:04
I also can't reproduce (ubuntu 22.04, py 3.10.4, pg 0.13.1, pyqt 5.15.7, qt 5.15.2). 
Closing this for now; let's reopen if it seems like there is something we can do to fix this.

**Closed by campagnola** 2022-10-02 17:04 UTC
Labels: cannot reproduce
