### ISSUE TITLE
plots not showing with NaN

### ISSUE THREAD

**Issue by summoningdark** [pyqtgraph/pyqtgraph#1057] opened 2019-10-15 19:52 UTC
### Short description

Plotting data with np.nan results in an empty plot.

### Code to reproduce

```python
import numpy as np
import pyqtgraph as pg

data = np.random.normal(size=1000)
data2 = np.random.normal(size=1000)
data2[0] = np.nan

pg.plot(data, title="no NaN")
pg.plot(data2, title="one NaN")

pg.QtGui.QApplication.exec_()
```

### Expected behavior

Two plots with random data.

### Real behavior

First plot shows as normal.
Second plot is empty.
```
An error occurred?
Post the full traceback inside these 'code fences'!
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0.dev0+ged6586c
 * Qt Python binding: PySide2 5.13.1 Qt 5.13.1
 * Python version: 3.7.3
 * NumPy version: 1.17.2
 * Operating system: Windows 10, x64
 * Installation method: python from python.org installer. numpy from pip. pyqtgraph from git and / "python setup.py install" in pyqtgraph directory

 * PyQtGraph version: 0.11.0.dev0+ged6586c
 * Qt Python binding: PySide2 5.13.1 Qt 5.13.1
 * Python version: 3.7.3
 * NumPy version: 1.17.2
 * Operating system: Centos 7
 * Installation method: python built from source. numpy from pip. pyqtgraph from git and / "python setup.py install" in pyqtgraph directory

### Additional context

**Comment by 2xB** [comment] 2019-10-17 00:05
I can reproduce this bug after updating from PyQt5 5.12.2 to PyQt5 5.13.1 under Windows 10.

**Comment by 2xB** [comment] 2019-10-17 00:08
This is a duplicate of an issue discussed in the comments of issue #1011 with @jongra. I would suggest to continue the analysis from there over here.

**Comment by 2xB** [comment] 2019-10-17 00:30
The issue seems to be that previously, Qt drawed the part of a path that it could draw, and now it does not draw anything if one part of the path is invalid. The path is created using `PlotCurveItem.getPath` and `PlotCurveItem.generatePath`, so if anyone comes up with a neat way to filter the path for `nan` entries, a Pull Request would certainly be welcome! Also, it would probably be an idea to allow for multiple paths to be generated, so if the curve is split by a np.nan value in the middle, it actually creates two seperated paths that are rendered without connection. For that, then also `PlotCurveItem.paint` would have to be adapted.
Just feel free to experiment with this and create a Pull Request!

**Comment by jongra** [comment] 2019-10-17 08:40
Plotting multiple paths, separated by np.nan values, can be achieved by the `pyqtgraph.PlotCurveItem` parameter `connect = "finite"`
See here: [pyqtgraph.PlotCurveItem.setData](http://www.pyqtgraph.org/documentation/graphicsItems/plotcurveitem.html#pyqtgraph.PlotCurveItem.setData)

**Comment by 2xB** [comment] 2019-10-17 13:52
@jongra That is true in theory. It would work this way: `functions.arrayToQPath(x, y, connect='finite')` would create a `QPainterPath` that contains `nan` values, but carries a connected=0 flag that prevents it from showing a connected line, so it is therefore invisible and effectively splits the path.
Now the issue is that `QPainterPath`s containing `nan` values are not painted at all, so a path that contains `nan` values that are not connected is still not drawn.

**Comment by summoningdark** [comment] 2019-10-17 18:50
I still see the issue with Pull Request #1058. I think the reason is that while the changes set connectivity flags for the offending points, the values are still NaN. Adding the following lines fixes it for the connect='finite', but would mess up the 'all', 'pairs' or connect=array cases:
```
arr[1:-1]['x'][non_finite_values] = 0
arr[1:-1]['y'][non_finite_values] = 0
```

**Comment by 2xB** [comment] 2019-10-18 16:44
@summoningdark Oh, I made a mistake. I did something similar to what you suggested, but my solution still fails if two non-finite values are side by side. As soon as I have time, I will have a look at how to fix that.

**Comment by 2xB** [comment] 2019-10-18 16:47
I am speaking about these lines in the PR:

```python3
    arr[1:-1]['x'][non_finite_values] = np.roll(x,-1)[non_finite_values]
    arr[1:-1]['y'][non_finite_values] = np.roll(y,-1)[non_finite_values]
```

**Comment by Fantasticer** [comment] 2019-12-10 13:54
I can fxi this bug after updating to PyQt5 5.13.0 under Windows 10.

**Comment by highfestiva** [comment] 2020-01-06 11:20
@Fantasticer How are things coming along? I'm short on time or I would try to help.

**Comment by Fantasticer** [comment] 2020-01-07 13:18
> @Fantasticer How are things coming along? I'm short on time or I would try to help.



> @Fantasticer How are things coming along? I'm short on time or I would try to help.

i think is just a bug in pyqt.Install the PyQt5 5.13.0  version is okay for nan

**Comment by chjaeggi** [comment] 2020-01-21 13:30
Any progress on this? Tested and observed on ubuntu 18.04 as well. It is OK for us to go back to 5.13.0 for now.

**Comment by j9ac9k** [comment] 2020-01-21 14:53
@highfestiva I think this is an upstream issue, afaik there is no pyqtgraph Dev effort going toward this issue for the time being.  I would love to know if the issue persists with 5.14.

**Comment by chjaeggi** [comment] 2020-01-21 15:09
For me it persists with PySide2==5.14.0. With the pyqtgraph PR branch https://github.com/pyqtgraph/pyqtgraph/pull/1058 (with failing tests) AND PySide2==5.14.0, however, everything works fine (except there is a lot of debug output about ignored exceptions).

**Comment by j9ac9k** [comment] 2020-01-21 20:09
Current tests are failing on 5.14.0 due to the changing of how PySide loads in .ui files, which is what our examples app uses (we use the examples app as part of the test suite).

**Comment by 2xB** [comment] 2020-01-24 12:56
@j9ac9k For me, the example from the **Code to reproduce** section above still fails. I think this issue exists since `Qt 5.13.1` - @Fantasticer, your solution of "updating to `Qt 5.13.0`" might actually work because you are using a version older than `Qt 5.13.1`. Could you test whether updating to a higher version for PyQt5 and Qt still works for you?

### Tested environment:

 * PyQtGraph version: branch `develop`, commit 6a2791e1c41ee5b08e860186c26613ddc4ef201d
 * Qt Python binding: PyQt5 5.14.1 Qt 5.14.0
 * Python version: 3.8.1
 * NumPy version: 1.18.1
 * Operating system: Manjaro Linux (5.4.12-1-MANJARO)
 * Installation method: `pyqtgraph via `setup.py`, rest via system packages

**Comment by raacampbell** [comment] 2020-03-04 15:02
I am seeing the problem too. PyQt5 v5.14.1   I've been using `connect="finite"` for a while and just noticed after a recent update that my plots are failing to appear. I traced it back to this issue.

**Comment by j9ac9k** [comment] 2020-03-04 16:20
@raacampbell thanks for reporting in; I suspect this is an upstream issue that we won't be able to do anything about, but I'll try and take a look at it and see if something comes up.

**Comment by cudmore** [comment] 2020-08-28 05:43
I am seeing the same bug. I can fix it by downgrading to PyQt 5.13.0 (but not 5.13.1) on macOS. Also seeing problems with newer versions of PyQt in Napari and downgrading to 5.13.0 also fixes those.

**Comment by StSav012** [comment] 2020-10-14 12:47
For PyQt 5.15.1 and pyqtgraph 0.11.0, the bug persists.

**Comment by highfestiva** [comment] 2020-10-20 21:15
Should we file this bug with (QtBase)[https://github.com/qt/qtbase/blob/dev/src/gui/painting/qpainterpath.cpp]? Anybody know how to file it properly for a quick resolution?

**Comment by j9ac9k** [comment] 2020-10-20 21:32
We have 3 PRs that relate to this issue in the queue (can't say for certain that those PRs would fix this issue); I'll nag some of the other maintainers that are more qualified to review/evaluate them and get them merged.  This issue is frankly what's holding up the 0.11.1 release in my mind.

**Comment by highfestiva** [comment] 2020-10-26 16:08
@j9ac9k any results nagging?

**Comment by j9ac9k** [comment] 2020-10-26 16:12
hi @highfestiva I'm still waiting to hear back from @campagnola I think they recently moved (as did I) so they may be a bit off the grid.  I have one more PR I want to fix/resolve/merge before I tackle this one, #1286 and #1287 (all of which are related).

**Comment by highfestiva** [comment] 2020-11-18 22:12
@j9ac9k In py3.9 (new stable) pyqt5.13.0 is no longer built and distributed to pypi. Can I dig into something myself, or is it mostly completed? All tests pass... Or should I ask someone else?

**Comment by j9ac9k** [comment] 2020-11-18 22:19
This issue is one of the show-stoppers for a 0.11.1 release.  I just need to figure out how to best resolve the PRs referenced above, and given it's low level integration into the library; it's something I'm a bit nervous on evaluating myself, as it has major compatibility and performance consequences that may not be obvious.

I'll likely look at integrating this myself once I resolve #1435

**Comment by highfestiva** [comment] 2020-11-18 23:33
I'd be happy to take it for a spin, but not sure which commits I should get (cherry-pick?), or if there's some clever way to try the related issues #1058, #1286 and #1287 in unison?

**Comment by j9ac9k** [comment] 2020-11-19 00:35
Won't be merging them all, as they have some overlap; figure out what overlaps and what is different between each PR, and of the overlapping content, figure out which PR works "better" (and for that I suggest on top of running the test suite, using `pyqtgraph.debug.Profiler` to try and evaluate which method performs faster.

**Comment by Nelson-numerical-software** [comment] 2020-11-20 16:48
Please merge and release an new package 🙏 
Patch is available since more one year (but no merge and no package).

**Comment by j9ac9k** [comment] 2020-11-22 05:43
I just benchmarked PR #1058 and #1287, with #1287 performing better in all cases, and taking a slight hit vs. master

Config  | #1058 | #1287 | master
-- | -- | -- | --
normal-all | 54.4012 ms | 23.4981 ms | 19.4948 ms
normal-pairs | 32.1891 ms | 14.744 ms | 12.7287 ms
normal-finite | 28.9152 ms | 11.0152 ms | 11.328 ms
half-nan-all | 103.5447 ms | 85.7241 ms | NA
half-nan-pairs | 94.1122 ms | 80.9419 ms | NA
half-nan-finite | 92.438 ms | 80.8871 ms | NA

The times are effectively the time it takes to make the diff of the commits...

The script I ran was, and I just used the profiler that's in `pyqtgraph.debug`.

```python
import numpy as np
import pyqtgraph as pg

pg.mkQApp()

def benchmarkArray(x, y):
    for connection in ["all", "pairs", "finite"]:
        print("Connection Type: {}".format(connection))
        pg.functions.arrayToQPath(x=x, y=y, connect=connection)

size = 1_000_000
print("{} million length array".format(size))
x = np.arange(size, dtype=float)
y = np.random.normal(size=x.shape[0])
benchmarkArray(x, y)

mask = np.random.choice(size, size // 2, replace=False)
x[mask] = np.nan
y[mask] = np.nan
benchmarkArray(x, y)
```

I want to give a special thank you to @zhujun98 for creating #1283 ..I had to rebase PR #1058 due to the changes, and the fixes that @zhujun98 made in that PR showed a significant performance improvement.

Also a thank you to @2xB and @campagnola for creating PRs to tackle this issue.  Before I merge #1287, I want to get input from other members here to see if there was a test case I should have tested that I did not (I did incorporate the suggested change from @abrauchli )

**Closed** 2020-11-23 04:27 UTC
Labels: bug

**Comment by highfestiva** [comment] 2020-11-23 12:26
@j9ac9k Lovely, thank you! Can we expect a release shortly?

**Comment by j9ac9k** [comment] 2020-11-23 17:04
Another release is definitely close; I think we may have addressed all noted regressions since 0.10.0.

There are a few other PRs I want to get merged before doing another release, 1453 and 1420, both of which are just about ready to merge. 

I'd also like to get 1437 (once we figure out why the test is failing) merged, and possibly 1404 (although I need to evaluate that one more.

The last PR I would really like to resolve is 1406; but I'm not sure why that is misbehaving.  If you have a python 3.9 environment setup locally, I would love some assistance with debugging why `test_reload` is failing with python3.9 + pyside2.

**Comment by zhujun98** [comment] 2020-11-23 20:12
@j9ac9k Thank you for the exciting benchmark result. It is my pleasure to contribute to a project which has been extensively used in scientific and engineering applications.

**Comment by highfestiva** [comment] 2020-11-27 07:58
@j9ac9k I'm all set up and ready to run tests, but don't know how. How do I run `test_reload` for instance?

**Comment by j9ac9k** [comment] 2020-11-27 08:00
> @j9ac9k I'm all set up and ready to run tests, but don't know how. How do I run `test_reload` for instance?

Probably should migrate this discussion to the other PR... but you install pytest and run `pytest -k "test_reload"` and that runs just that one test...
