### ISSUE TITLE
chage ArrowItem rotation by setStyle(angle=ag) cannot work

### ISSUE THREAD

**Issue by SdKay** [pyqtgraph/pyqtgraph#794] opened 2018-12-07 02:07 UTC
create an arrow item
`
 deePosArrow = pg.ArrowItem(angle=0, tipAngle=30, baseAngle=20, headLen=15, tailLen=None, pen={'color': 'b'})
deePosArrow.setPos(400, 400)
view.addItem(deePosArrow)
`
i want to change it rotation when data update by:
`
        global deePosArrow
        deePosArrow.setPos(position[0], position[1])
        deePosArrow.setStyle(angle=position[2]*180/3.14)
`
setPos is worked, but setStyle didn't work, even directly using `deePosArrow.setStyle(angle=90)` it still remains like angle=0 style

**Comment by yuanchao** [comment] 2021-01-13 22:44
I've got the same problem with pyqtgraph (0.10.0). Also, when maximize the window, the size of the arrow is not resized respectively even when pxMode=True. (Ubuntu 18.04.5)

**Comment by ixjlyons** [comment] 2021-01-15 02:52
This was fixed with ea9e8a7, so upgrading to 0.11.0+ should resolve the issue.

@yuanchao could you be a little more specific with the pxMode issue? With `pxMode=True` (the default), the arrow should stay the same size *on the screen* regardless of zoom or window size. With `pxMode=False`, the arrow should keep its size *in plot coordinates* so zooming or resizing the window causes the arrow to change size/shape on the screen. I believe this is the intended behavior and it seems to work for me back to 0.10.0. If that's not what you're observing, could you create a new issue, maybe with a screenshot or two to show what's going on?

I'll close this because the original issue with the angle not updating looks to be resolved.

**Closed by ixjlyons** 2021-01-15 02:52 UTC
