### ISSUE TITLE
Mac OS -X pyqt4 broken

### ISSUE THREAD

**Issue by CPrescher** [pyqtgraph/pyqtgraph#375] opened 2016-09-13 06:35 UTC
Hei there,

I have a problem with my MacOS X version of my program it always gives the following error and several things seem to be broken:

Sep 13 08:32:10  python[11018] <Error>: void CGPathAddLineToPoint(CGMutablePathRef _Nullable, const CGAffineTransform \* _Nullable, CGFloat, CGFloat): no current point.

This error is send basically every interaction with an Image Widget.

Do you experience the same? Is there a solution other than switching to pyqt5?

**Comment by j9ac9k** [comment] 2019-06-07 23:17
Hi, I haven't had this kind of issue, and our pyqt4 CI runs just fine.  If you can generate a reproducible event/code can you give us more information like pyqtgraph version, qt-bindings version and some code to try and reproduce?

I'm going to close this specific issue due to it's age, but if you are still experiencing this problem please open a new one. 

Thanks

**Closed by j9ac9k** 2019-06-07 23:17 UTC
