### ISSUE TITLE
Zooming in a large image turns display blank

### ISSUE THREAD

**Issue by pramodbutte** [pyqtgraph/pyqtgraph#1008] opened 2019-08-03 23:02 UTC
I am making an application in which I have a large (4k x 4k) resolution pathology images. I would like to zoom in these images, but if I use a full resolution image then as I zoom in the image display goes blank. if I reduce the size to 1/3, then I am able to zoom in all the way.

here is an example: [example] (https://youtu.be/Cq5YRYgehvM)

Whats the best way to handle large images?

Thanks,
Pramod

**Comment by 2xB** [comment] 2019-08-04 16:04
Hello Pramod,
Could you please provide a minimal working example that I can execute to reproduce what you observe? It would also be great if you filled out the default issue template (that you see when you create a new issue), because you could there provide information on which system you use.
Best regards!

**Comment by pramodbutte** [comment] 2019-08-04 20:19
Its part of a big application, but I will try to extract the relevant code and post it.

**Comment by 2xB** [comment] 2019-08-20 15:55
@pramodbutte Okay, that sounds good! If one can help with that, just leave a comment.

**Comment by j9ac9k** [comment] 2021-03-20 16:18
I'm going to close this out, we haven't seen images disappear with large images, we have seen some line plots disappear with large zoom factors; but #1140 was introduced to work around that.  @pramodbutte if you can provide an example that we can reproduce the issue with, I'll re-open 👍🏻

**Closed by j9ac9k** 2021-03-20 16:18 UTC
