### ISSUE TITLE
No syntax hint

### ISSUE THREAD

**Issue by bw-xu** [pyqtgraph/pyqtgraph#2558] opened 2022-12-23 19:18 UTC
### Short description

There is not syntax hint when using `pg.GraphicsObject` and other classes.

### Code to reproduce

```python
import pyqtgraph as pg

label = pg.TextItem(fill=pg.mkBrush((50,50,200,128)))
self.label.setZValue(50)
```

### Expected behavior

There should be grammar hint when I input `setZValue`

### Real behavior

No hint occurs

### Tested environment(s)

 * PyQtGraph version:  0.13.1 
 * Qt Python binding:  PySide6/PyQt6 
 * Python version: 3.8/3.11
 * Operating system: MacOS
 * Editor: VSCode, Pylance v2022.12.20
 * Installation method: pip install pyqtgraph 

### Additional context

This is because pyqtgraph/Qt/QtWidgets/__init__.py is empty

**Comment by pijyoi** [comment] 2022-12-25 20:25
There is https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/Qt/__init__.pyi but it is not bundled into the wheel.

**Comment by j9ac9k** [comment] 2022-12-25 21:10
Also that stub only works for pycharm as far as I’m aware. Vscode doesn’t
read stub files in the same project for type hints.

**Comment by j9ac9k** [comment] 2023-06-06 01:26
Closing as duplicate of #2409

**Closed by j9ac9k** 2023-06-06 01:26 UTC
