### ISSUE TITLE
A GraphicsItem object overlaps the ViewBox border line

### ISSUE THREAD

**Issue by espdev** [pyqtgraph/pyqtgraph#316] opened 2016-04-19 17:14 UTC
An example:

``` python
from pyqtgraph.Qt import QtGui
import pyqtgraph as pg
from skimage import data

app = QtGui.QApplication([])

pg.setConfigOptions(antialias=True)

view = pg.GraphicsView()
view.resize(500, 500)

border = pg.mkPen(cosmetic=True, width=5, color='g')

glayout = pg.GraphicsLayout(border=border)
view.setCentralItem(glayout)

vb1 = pg.ViewBox(lockAspect=True, invertY=True)
vb2 = pg.ViewBox(lockAspect=True, invertY=True)

glayout.addItem(vb1, 0, 0)
glayout.addItem(vb2, 0, 1)

imi1 = pg.ImageItem()
imi1.setImage(data.camera().T)
vb1.addItem(imi1)

imi2 = pg.ImageItem()
imi2.setImage(data.camera().T)
vb2.addItem(imi2)

view.show()
app.exec()
```

Screenshot:
<img width="300" alt="pg_overlapping" src="https://cloud.githubusercontent.com/assets/1299189/14648472/24270754-066b-11e6-9ca7-e678853a18da.PNG">

**Comment by sylm21** [comment] 2016-04-21 09:38
No problem for me with your script with the last pyqtgraph develop version. I'm on windows 7 with pyqt5.5 and python 3.4

**Comment by espdev** [comment] 2016-04-21 12:59
@sylm21 Thank you for testing. My environment: windows 10, pyqtgraph 0.9.10-142-gfd76443, pyqt 5.5.1 and python 3.4. I use antialiasing and do not use opengl.

Currently I'm using workaround: double layout:
```python
view = pg.GraphicsView(self)

glayout = pg.GraphicsLayout(border=(150, 150, 150))
view.setCentralItem(glayout)

layout = glayout.addLayout(row=0, col=0)
layout.setContentsMargins(1, 1, 1, 1)

viewbox = pg.ViewBox()
layout.addItem(viewbox)
```

**Comment by campagnola** [comment] 2016-04-22 17:21
Confirmed on linux. This could be fixed easily by removing the border drawing from `ViewBox.paint()` and instead adding a child `QGraphicsRectItem` similar to `ViewBox.background`, with the Z value set high.  @espdev, would you like to make a PR?

**Comment by espdev** [comment] 2016-04-22 21:07
@campagnola GraphicsLayout has the same problem.

I tried to fix this problem for ViewBox using your method, but there is new problem. Depending on the size of the window some borders disappear.
<img width="300" alt="pg1" src="https://cloud.githubusercontent.com/assets/1299189/14754785/41d867f2-08e6-11e6-90d1-a3f72492eafe.PNG">

My changes at ViewBox:
```python
# __init__
...
self.borderRect = QtGui.QGraphicsRectItem(self.rect())
self.borderRect.setParentItem(self)
self.borderRect.setZValue(1e3)
self.borderRect.setPen(self.border)
...

# resizeEvent
...
self.borderRect.setRect(self.rect())
...

# paint
...
# if self.border is not None:
#     bounds = self.shape()
#     p.setPen(self.border)
#     #p.fillRect(bounds, QtGui.QColor(0, 0, 0))
#     p.drawPath(bounds)
...
```

**Comment by campagnola** [comment] 2016-04-24 21:08
Ah, right--this is because the ViewBox clips its children to its own shape. That's probably why I had it draw its own border in the first place. You can get around this by having `ViewBox.childGroup` do the clipping instead. First remove the line in `ViewBox.__int__` that sets `ItemClipsChildrenToShape`, then put it in the `ChildGroup` class instead, along with some methods to ensure that the child group has the same shape as the viewbox:

    class ChildGroup(ItemGroup):
        def __init__(self, parent):
            ItemGroup.__init__(self, parent)
            self.setFlag(self.ItemClipsChildrenToShape)

        . . .
    
        def shape(self):
            return self.mapFromParent(self.parentItem().shape())
    
        def boundingRect(self):
            return self.mapRectFromParent(self.parentItem().boundingRect())

Finally, at the end of `ViewBox.resizeEvent`, add this:

    self.childGroup.prepareGeometryChange()

I *think* this will all work, but it will need to be carefully tested.

**Comment by espdev** [comment] 2016-04-24 22:19
@campagnola I checked the method with ChildGroup. It seems like it works!

**Comment by campagnola** [comment] 2016-04-25 01:50
Cool! want to turn it into a PR?

**Comment by j9ac9k** [comment] 2019-06-27 05:33
As #321 is merged, we can close this.  Thanks again for the issue/PR!

**Closed by j9ac9k** 2019-06-27 05:33 UTC
