### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'apoptose'

### ISSUE THREAD

**Issue by SchrodingersGat** [pyqtgraph/pyqtgraph#1702] opened 2021-04-09 04:55 UTC
### Short description

When closing a Dock (programatically, not using the "close" button), throws the error as described in the title.

### Expected behavior

Dock window should close

### Real behavior

Throws AttributeError, dock does not close

```
  File "C:\...\Python\Python38-32\lib\site-packages\pyqtgraph\dockarea\Dock.py", line 236, in close
    self._container.apoptose()
AttributeError: 'NoneType' object has no attribute 'apoptose'
```

### Tested environment(s)

 * PyQtGraph version: 0.12.1
 * Python version: 3.6
 * NumPy version: 1.19.4
 * Operating system: Windows 10
 * Installation method: PIP

### Additional context

`self._container` is None, but there are no checks for a null container in `Dock.close()`

Also, in `Dock.__init__`, there are two separate lines `self._container = None` (might be worth deleting one of these)

**Comment by j9ac9k** [comment] 2021-04-09 04:58
I've run into this very issue when trying to close an already closed Dock (which admittedly, should not raise an exception either).  I am curious how this error occurred if the dock was already open.  Was there anything else odd about it; like ...was there no widget within it?

**Comment by SchrodingersGat** [comment] 2021-04-09 05:03
There are two pg.PlotWidget attached to the dock

**Comment by j9ac9k** [comment] 2021-04-09 05:07
How do you have two plot widgets?  The Dock can only have one widget at most 1 widget at a time.  Do you mean you have a GraphicsWidgetLayout with two plots in it?

**Comment by SchrodingersGat** [comment] 2021-04-09 05:42
Interestingly, this behaviour does not exhibit if there is only a single widget attached to the dock..

With a single widget, the dock closes correctly when .close() is called programatically

**Comment by max-radin** [comment] 2021-11-13 23:29
Has anyone been able to reproduce this error? The example below worked ok for me both on master and pyqtgraph-0.12.1.

```python
import numpy as np
import pyqtgraph as pg
from pyqtgraph.dockarea.Dock import Dock
from pyqtgraph.dockarea.DockArea import DockArea
from pyqtgraph.Qt import QtWidgets

app = pg.mkQApp("DockArea Example")
win = QtWidgets.QMainWindow()
area = DockArea()
win.setCentralWidget(area)
win.resize(1000,500)
win.setWindowTitle('dock with two plots')


d1 = Dock("Dock1", size=(1, 1))
d2 = Dock("Dock5", size=(500,200))
area.addDock(d1, 'left')
area.addDock(d2, 'right', d1)

w1 = pg.LayoutWidget()
closeBtn = QtWidgets.QPushButton('Close dock')
w1.addWidget(closeBtn, row=1, col=0)
d1.addWidget(w1)
state = None
def close():
    d2.close()
closeBtn.clicked.connect(close)

w1 = pg.PlotWidget(title="Random data")
w1.plot(np.random.normal(size=100))
w2 = pg.PlotWidget(title="Random data")
w2.plot(np.random.normal(size=100))

d2.addWidget(w1)
d2.addWidget(w2)

win.show()

if __name__ == '__main__':
    pg.exec()

    # For pyqtgraph-0.12.1
    # pg.mkQApp().exec_()
```

**Comment by j9ac9k** [comment] 2021-11-14 02:46
@max-radin great use of code, but I can actually cause the fault with your example, press "close dock" twice

```
Traceback (most recent call last):
  File "dockarea_troubleshooting.py", line 26, in close
    d2.close()
  File "/Users/ogi/Developer/pyqtgraph/pyqtgraph/dockarea/Dock.py", line 233, in close
    self._container.apoptose()
AttributeError: 'NoneType' object has no attribute 'apoptose'
```

**Comment by max-radin** [comment] 2021-11-14 19:16
Ah that's right, if you try to close it twice it will raise an exception. It looks like another scenario where you get this exception is if you try to close a dock that was never added to a DockArea. It's not clear to me though if this is what @SchrodingersGat was experiencing - they seemed to be saying that an already open dock was failing to close.

**Comment by j9ac9k** [comment] 2021-11-14 19:22
> Ah that's right, if you try to close it twice it will raise an exception. It looks like another scenario where you get this exception is if you try to close a dock that was never added to a DockArea. It's not clear to me though if this is what @SchrodingersGat was experiencing - they seemed to be saying that an already open dock was failing to close.

Without the MWE it's hard to say for sure; but I suspect the dock was either never added, or there were multiple calls to close it, raising this exception.

**Closed** 2021-11-14 21:23 UTC
Labels: good first issue, Dock
