### ISSUE TITLE
Crash when applying fft to odd number of values serie

### ISSUE THREAD

**Issue by racingchuck** [pyqtgraph/pyqtgraph#433] opened 2017-01-30 21:17 UTC
Windows 10, Python 3.6 , PyQt 5.7.1, pyqtgraph 0.10 via pip

When applying transform to a series with odd number of values, python crashes with the following error:

<class 'TypeError'> slice indices must be integers or None or have an __index__ method <traceback object at 0x053F74E0>
Traceback (most recent call last):
  File "C:\Users\cratelle\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 891, in updateSpectrumMode
    c.setFftMode(b)
  File "C:\Users\cratelle\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 205, in setFftMode
    self.updateItems()
  File "C:\Users\cratelle\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 483, in updateItems
    x,y = self.getData()
  File "C:\Users\cratelle\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 525, in getData
    x,y = self._fourierTransform(x, y)
  File "C:\Users\cratelle\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 683, in _fourierTransform
    y = abs(f[1:len(f)/2])
TypeError: slice indices must be integers or None or have an __index__ method

[Minimal code](https://gist.github.com/racingchuck/fd1f51faf87b44a103001f970eba5409)

Here is a link for a minimal working example which creates a QGraphicsWindow, add a plot with random data from pyqtgraph,  then displays the plot. The error can be reproduced by right-clicking "Plot Options" >>"Transform">>"Power Spectrum (FFT)"

**Comment by pijyoi** [comment] 2017-02-03 01:59
this should be fixed by pull request #429

**Comment by j9ac9k** [comment] 2019-06-17 17:41
Thanks for the issue.

We cannot reproduce the issue, but since another contributor referenced a PR that should have addressed this issue, I'm going to close this out.  If you still have this problem, feel free to post an example of how to generate the error.

**Closed by j9ac9k** 2019-06-17 17:41 UTC
Labels: cannot reproduce
