### ISSUE TITLE
PySide/Python2.7 compatibility error: axis item not showing in plotItem

### ISSUE THREAD

**Issue by josepNTU** [pyqtgraph/pyqtgraph#1192] opened 2020-05-08 08:11 UTC
PyQtGraph not showing the axis lines and grid (but the labels do show). I'm posting a slightly modified version of the PlotItem example from the documentation. The original example didn't work either. I added an axisItem explicitly to check if it would work, but it didn't. 

I have run the same code in Spyder (Python 3.7/PyQt5) and there it works great. Unfortunately, I cannot move from Python 2.7 in my current project. 

I already posted a report weeks ago with a  similar problem. I upgraded to pyqtgraph==0.11.0rc0. This solved the issue of no graph plotted at all, but the axis is still not there.

### Short description
PyQtGraph not showing the axis lines and grid (but the labels do show). I'm posting a slightly modified version of the PlotItem example from the documentation. The original example didn't work either. I added an axisItem explicitly to check if it would work, but it didn't. 

### Code to reproduce
```python
# -*- coding: utf-8 -*-
"""
Demonstrates use of PlotWidget class. This is little more than a
GraphicsView with a PlotItem placed in its center.
"""


##import initExample ## Add path to library (just for examples; you do not need this)


from pyqtgraph.Qt import QtGui, QtCore
import numpy as np
import pyqtgraph as pg

#QtGui.QApplication.setGraphicsSystem('raster')
app = QtGui.QApplication([])
mw = QtGui.QMainWindow()
mw.setWindowTitle('pyqtgraph example: PlotWidget')
mw.resize(800,800)
cw = QtGui.QWidget()
mw.setCentralWidget(cw)
l = QtGui.QVBoxLayout()
cw.setLayout(l)

ax = pg.AxisItem('left', maxTickLength=-10)
ax.setGrid(255)
ax.setPen(0,255,255)
ax.setLabel(text='Wishy-washy', units='PURR', unitPrefix='ss')
ax.setWidth(3)
axdict = {}
axdict['left'] = ax

pw = pg.PlotWidget(name='Plot1', axisItems=axdict)  ## giving the plots names allows us to link their axes together
l.addWidget(pw)
pw2 = pg.PlotWidget(name='Plot2')
l.addWidget(pw2)
pw3 = pg.PlotWidget()
l.addWidget(pw3)



mw.show()

## Create an empty plot curve to be filled later, set its pen
p1 = pw.plot()
p1.setPen((100,200,100))

## Add in some extra graphics
rect = QtGui.QGraphicsRectItem(QtCore.QRectF(0, 0, 1, 5e-11))
rect.setPen(pg.mkPen(100, 200, 100))
pw.addItem(rect)

##pw.setLabel('left', 'Value', units='V')
pw.setLabel('bottom', 'Time', units='s')
pw.setXRange(0, 2)
pw.setYRange(0, 1e-10)

def rand(n):
    data = np.random.random(n)
    data[int(n*0.1):int(n*0.13)] += .5
    data[int(n*0.18)] += 2
    data[int(n*0.1):int(n*0.13)] *= 5
    data[int(n*0.18)] *= 20
    data *= 1e-12
    return data, np.arange(n, n+len(data)) / float(n)


def updateData():
    yd, xd = rand(10000)
    p1.setData(y=yd, x=xd)

## Start a timer to rapidly update the plot in pw
t = QtCore.QTimer()
t.timeout.connect(updateData)
t.start()
#updateData()

## Multiple parameterized plots--we can autogenerate averages for these.
for i in range(0, 5):
    for j in range(0, 3):
        yd, xd = rand(10000)
        pw2.plot(y=yd*(j+1), x=xd, params={'iter': i, 'val': j})

## Test large numbers
curve = pw3.plot(np.random.normal(size=100)*1e0, clickable=True)
curve.curve.setClickable(True)
curve.setPen('w')  ## white pen
curve.setShadowPen(pg.mkPen((70,70,30), width=6, cosmetic=True))

def clicked():
    print("curve clicked")
curve.sigClicked.connect(clicked)

lr = pg.LinearRegionItem([1, 30], bounds=[0,100], movable=True)
pw3.addItem(lr)
line = pg.InfiniteLine(angle=90, movable=True)
pw3.addItem(line)
line.setBounds([0,200])

## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()
```

### Expected behavior
As in the documentation

### Real behavior
Axis not showing

### Tested environment(s)

 * PyQtGraph version: pyqtgraph==0.11.0rc0
 * Qt Python binding: PySide==1.2.4
 * Python version: 2.7
 * NumPy version: numpy==1.16.6
 * Operating system: Windows 10
 * Installation method: pip install

### Additional context
![image](https://user-images.githubusercontent.com/62689146/81385787-85fe5f80-9146-11ea-9ab4-7dd88f4b331e.png)

**Comment by 2xB** [comment] 2020-05-09 21:01
I was so bold to add code fences to your code so it is formatted correctly (by adding
` ```python3 ` before and  ` ``` ` after the code).

**Comment by j9ac9k** [comment] 2020-05-10 15:54
Oof, we should definitely aim to tackle this before 0.11 release.

**Comment by josepNTU** [comment] 2020-05-11 08:04
thanks guys :)

**Comment by j9ac9k** [comment] 2020-05-30 04:33
so on macOS I can't replicate, running your exact code:

![image](https://user-images.githubusercontent.com/646398/83319504-f2bfc380-a1f3-11ea-890a-6c5920b693a4.png)

Of course after I attempted to replicate, I saw you were on Windows 10... will try to replicate there.

**Comment by j9ac9k** [comment] 2020-05-30 04:49
Ok, I can't reproduce on windows 10 either.

![image](https://user-images.githubusercontent.com/646398/83319717-b4c39f00-a1f5-11ea-95dd-54c07c087fb9.png)

Can you talk about how you create this environment?  Recreating the python2/pyside1 environments reliably in our CI process has been a challenge.

I have to create these environments using conda, with a config enabling the use of the free channel (`conda config --set restore_free_channel true`).  On macOS (and **only** macOS) I need to pre-pend conda forge `conda config --prepend channels conda-forge`.  

I then install all the dependencies via conda

```
conda install pyside numpy scipy pyopengl h5py six --yes --quiet
```

output of my conda list.

```
(py2-pyqtgraph) C:\Users\ogi>conda list
# packages in environment at C:\Users\ogi\.conda\envs\py2-pyqtgraph:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2020.1.1                      0
certifi                   2019.11.28               py27_0
h5py                      2.7.0               np113py27_0
hdf5                      1.8.15.1                  vc9_4
mkl                       2017.0.3                      0
numpy                     1.13.1                   py27_0
pip                       19.3.1                   py27_0
pyopengl                  3.1.1a1                  py27_0
pyqtgraph                 0.11.0rc0                pypi_0    pypi
pyside                    1.2.1                    py27_0
python                    2.7.18               hfb89ab9_0
scipy                     0.19.1              np113py27_0
setuptools                44.0.0                   py27_0
six                       1.10.0                   py27_0
sqlite                    3.30.1               h0c8e037_0
vc                        9                    h7299396_1
vs2008_runtime            9.00.30729.1         hfaea7d5_1
wheel                     0.33.6                   py27_0
wincertstore              0.2              py27hf04cefb_0
zlib                      1.2.11               h3cc03e0_3
```

Note that the pyside version is 1.2.1, not 1.2.4.

**Comment by j9ac9k** [comment] 2020-06-04 22:50
I'm going to close this issue since we can't reproduce and it's involving some _ancient_ Qt bindings which we have observed having trouble with ourselves.  

I will say that 0.11 does support pyside1 bindings, as we do test against it (OpenGL stuff on macOS with python2 is an exception).  You can see my earlier post in the issue with how to replicate our test environment.  If you run into issues there, or identify a fix for the issue presented, we would certainly be interested.

Sorry we can't be of more assistance.

**Closed by j9ac9k** 2020-06-04 22:50 UTC
Labels: bug, cannot reproduce, high-priority
