### ISSUE TITLE
    if self.container().type() == 'tab': AttributeError: 'NoneType' object has no attribute 'type'

### ISSUE THREAD

**Issue by arielja87** [pyqtgraph/pyqtgraph#833] opened 2019-02-19 14:03 UTC
Not sure why I was seeing this or why no one else had. But I seem to have solved the problem by just adding a check that container is not None on line 155 of Dock.py. 

            if self.container() is not None and self.container().type() == 'tab':

**Comment by UsYer** [comment] 2019-02-24 10:52
Just letting you know, that I have observed the same problem, so thank you for the tip.
Did you notice any other problems if you continue executing the code? When the exceptions is raised the rest of the code is skipped.

What I am wondering is how self.container() can return None when adding a new dock?
I fear this check just hides the underlying problem and I would like to know what causes it.
But I haven't spend the time to properly investigate.

**Comment by Oscar438** [comment] 2019-05-23 07:51
I have also encountered the same issue, I fixed it by chaning the setOrientation() function to:

    def setOrientation(self, o='auto', force=False):
        """
        Sets the orientation of the title bar for this Dock.
        Must be one of 'auto', 'horizontal', or 'vertical'.
        By default ('auto'), the orientation is determined
        based on the aspect ratio of the Dock.
        """
        #print self.name(), "setOrientation", o, force
        if o == 'auto' and self.autoOrient:
            if 'type' in dir(self.container()):
                if self.container().type() == 'tab':
                    o = 'horizontal'
                elif self.width() > self.height()*1.5:
                    o = 'vertical'
                else:
                    o = 'horizontal'
            elif self.width() > self.height() * 1.5:
                o = 'vertical'
            else:
                o = 'horizontal'
        if force or self.orientation != o:
            self.orientation = o
            self.label.setOrientation(o)
            self.updateStyle()

**Comment by 2xB** [comment] 2019-06-04 12:47
Did you also look into why this happens? From my intuitive understanding, `container` should be an instance of one of the classes defined in https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/dockarea/Container.py, and therefore have a `type` method.

**Comment by Oscar438** [comment] 2019-06-25 06:59
Not sure about @arielja87 but my problem was trying to add the dock to an area immediately after it has been closed using the sigClosed signal. 

In the context of `examples/dockarea.py` it would go something like this:
```python
def d6_closed():
    area.addDock(d6, 'top', d4)

win.show()

d6.sigClosed.connect(d6_closed)
```

I should probably rejig how I'm operating, but is this behaviour intended?

**Comment by ixjlyons** [comment] 2019-06-27 23:02
I see, thanks. I'm able to reproduce the issue now. When the `Dock` is closed, it does some cleanup which includes setting its `_container` to `None`. I don't think that should be changed. When it is re-inserted into a container, `setOrientation` is getting called before `containerChanged` (the latter sets the `_container` attribute to not `None`), resulting in the error.

Now, the proposed fix does seem like a bit of a bandage over the underlying issue, I'm thinking it may work fine because once `containerChanged` *does* end up getting called, *it* will call `setOrientation`. That is, I'm not seeing any unintended side effects.

@arielja87 @UsYer: any examples of other use cases where this issue occurs would be helpful. Re-inserting a closed dock is a somewhat odd case so I'm curious if there are others.

**Comment by Aikhjarto** [comment] 2020-06-05 09:01
@ixjlyons This issues seems to also happen when adding a Dock that forces other Docks to resize.
```python
import pyqtgraph as pg
from pyqtgraph.dockarea import DockArea, Dock
from pyqtgraph.Qt import QtGui, QtCore, QtWidgets


app = QtGui.QApplication([])
area=DockArea()
d1=Dock('Dock1', size=(100,100))
area.addDock(d1,'left')
area.show()

d2=Dock('Dock2', size=(100,100))
area.addDock(d2,'right',d1)

import sys
if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
    QtGui.QApplication.instance().exec_()
```

Tested with pyqtgraph 0.11.0rc0

**Comment by ixjlyons** [comment] 2020-06-20 19:30
Thank you for the example. This demonstrates that it's not just an issue with closing/cleaning up docks but in their initialization as well. As a workaround, moving the `area.show()` line to the end seems to get rid of the error message.

I revisited the problem with this example and found that reordering the following two lines gets rid of the error but seems to cause some other issues when moving docks around (specifically: moving one dock into another to change to tabs then moving it back out):

https://github.com/pyqtgraph/pyqtgraph/blob/e5a132704149224329ef50373abfc44e47be1c48/pyqtgraph/dockarea/Container.py#L48-L50

I'm inclined to accept the proposed fix. Once the container is set, `setOrientation` will be triggered again anyway. However, I would prefer the original proposal checking `if self.container() is None` to `if 'type' in dir(self.container())` (in #900). I'll create a new pull request for that.

**Closed** 2020-06-23 02:58 UTC
