### ISSUE TITLE
Removing and adding a GLScatterPlotItem removes a GLViewWidget's GLGridItems

### ISSUE THREAD

**Issue by DoC-Noah** [pyqtgraph/pyqtgraph#1018] opened 2019-08-13 17:38 UTC
### Short description
This bug is mercurial and will not occur if you're only using one ScatterPlotItem, or if you toggle the second instead of the first, or if you immediately remove and then show the first item before toggling it, ...

Looks related to  #103 and #145

### Code to reproduce

```python
from pyqtgraph.Qt import QtCore, QtGui, QtWidgets
import pyqtgraph.opengl as gl
import pyqtgraph as pg
import numpy as np

app = QtGui.QApplication([])
w = gl.GLViewWidget()
w.show()
w.setWindowTitle('GLScatterPlotItem making GLGridItem invisible example')

gx = gl.GLGridItem()
w.addItem(gx)


window = QtWidgets.QMainWindow()

plt1 = gl.GLScatterPlotItem(pos=np.zeros((1, 3)))
plt2 = gl.GLScatterPlotItem(pos=np.zeros((1, 3)))
plt3 = gl.GLScatterPlotItem(pos=np.zeros((1, 3)))
w.addItem(plt1)
w.addItem(plt2)
w.addItem(plt3)

show = False
def toggle():
    global show
    if show:
        w.addItem(plt2)
    else:
        w.removeItem(plt2)
    show = not show

ok = QtWidgets.QPushButton('Ok')
ok.clicked.connect(toggle)

window.setCentralWidget(ok)

if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        window.show()
        QtGui.QApplication.instance().exec_()
```

Click the button twice and the grids disappear.

### Tested environment(s)

 * PyQtGraph version: 0.11.0.dev0+gad7453c
 * Qt Python binding: PySide2 5.13.0 Qt 5.13.0
 * Python version: 3.7.4 x64
 * NumPy version: 1.17.0
 * Operating system: Windows 10
 * Installation method: 

*edit by ixjlyons: code fences around the example code*

**Comment by 2xB** [comment] 2019-08-13 20:49
I could not reproduce this on

- PyQt5 5.12.2 Qt 5.12.3
- Python 3.6.5
- Windows 10

and
 - PySide2 5.13.0 Qt 5.13.0
 - Python 3.7.4
 - Manjaro Linux (Arch)

**Comment by 2xB** [comment] 2019-08-13 20:50
It might be caused by PySide2?

**Comment by 2xB** [comment] 2019-08-13 21:03
Could not reproduce on

- PySide2 5.13.0 Qt 5.13.0
- Python 3.6.5
- Windows 10

@DoC-Noah How often does this occur if you try it? If you rotate the view via the left mouse button, does the grid reappear?

**Comment by DoC-Noah** [comment] 2019-08-14 21:34
I re-ran the code and it actually worked. But after adding another GLScatterPlotItem, it doesn't work. I updated my comment above to include a third point.

The error has occurred every time I've tried it (except the first time I ran it just now). 
Rotating the view does not make the grid reappear for me.

**Comment by 2xB** [comment] 2019-08-15 00:21
After correcting the one `pl3 = ...` to `plt3 = ...`, I could reproduce this with the new code on the following system!

 - PySide2 5.13.0 Qt 5.13.0
 - Python 3.6.5
 - Windows 10

**Comment by 2xB** [comment] 2019-08-15 00:49
Could you please verify that Pull Request #1019 fixes this bug?

**Comment by DoC-Noah** [comment] 2019-08-16 14:34
It works! :) :)

**Comment by 2xB** [comment] 2019-08-16 21:05
That is great!

Usually, an issue is left open until the according Pull Request is merged, because while it is not merged, the issue persists, and sometimes the Pull Request is not even merged in the near future.

**Comment by DoC-Noah** [comment] 2019-08-16 21:09
Oh whoops, thanks!

**Closed** 2019-08-17 03:19 UTC
Labels: bug, openGL
