### ISSUE TITLE
TableWidget throws error on calling save

### ISSUE THREAD

**Issue by ntjess** [pyqtgraph/pyqtgraph#1106] opened 2020-01-04 19:09 UTC
### Short description

This is a pretty simple issue. When selecting data in a `TableWidget` and choosing 'Save', the following error appears:

`TypeError: expected str, bytes or os.PathLike object, not tuple`

This is because the filename is retrieved from QFileDialog.getSaveFileName, which returns a tuple instead of only a filename.

### Code to reproduce
```
import pyqtgraph as pg
app = pg.mkQApp()
t = pg.TableWidget()
t.setData([[1,2,3], [4,5,6]])
t.show()
app.exec()
```
Right-click the table area and select 'save'
Enter a filename

The error will appear:

```
Traceback (most recent call last):
  File "C:\Users\...\pyqtgraph\widgets\TableWidget.py", line 340, in saveSel
    self.save(self.serialize(useSelection=True))
  File "C:\Users\...\pyqtgraph\widgets\TableWidget.py", line 350, in save
    open(fileName, 'w').write(data)
TypeError: expected str, bytes or os.PathLike object, not tuple
```

### Tested environment(s)

 * PyQtGraph version: 0.10.0
 * Qt Python binding: PyQt5
 * Python version: 3.7.4
 * NumPy version: 1.16.5
 * Operating system: Windows 10 build 1909
 * Installation method: Conda

**Comment by ixjlyons** [comment] 2020-01-04 22:34
Duplicate of #714 (resolved by #715). This will be fixed in the upcoming release. Thanks for the detailed report.

**Closed by ixjlyons** 2020-01-04 22:34 UTC
Labels: duplicate
