### ISSUE TITLE
rqt_plot export using PyQtGraph TypeError

### ISSUE THREAD

**Issue by svisschers** [pyqtgraph/pyqtgraph#651] opened 2018-03-28 12:53 UTC
Through the steps explained in the rqt_plot I raised:
https://github.com/ros-visualization/rqt_plot/issues/11

I try to export the plotted graph, regardless of output format (.png or .csv file), the actions result in the following error:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pyqtgraph/exporters/Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "/usr/lib/python2.7/dist-packages/pyqtgraph/exporters/ImageExporter.py", line 70, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
TypeError: 'float' object cannot be interpreted as an index` 

The owner of the rqt_plot repository alerted me to the fact that the problem is caused by your package. Do you know what the problem is?

Many thanks.

**Comment by raphaelvalentin** [comment] 2018-04-24 13:57
Quick fix that works for me:

```
        # FIX cause bug with pyqtgraph
        for p in exporter.params.children():
            if p.name() in ('width', 'height'):
                p.opts['value'] = int(p.opts['value'])
```

**Comment by andrewleech** [comment] 2018-05-17 06:55
I've run into the same issue. It's caused in: `pyqtgraph.exporters.ImageExporter.ImageExporter`

both `widthChanged()` and `heightChanged()` force the parameters to be `float`.

Then in `export()` the following line fails:
`bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)`
`{TypeError}'float' object cannot be interpreted as an integer`

**Comment by andrewleech** [comment] 2018-05-17 08:06
This is a duplicate of #464

**Comment by campagnola** [comment] 2018-05-18 02:59
I believe this is already fixed in the `develop` branch; please reopen if I misunderstood the issue.

**Closed by campagnola** 2018-05-18 02:59 UTC
