### ISSUE TITLE
Completely broken on PySide6>=6.5.0

### ISSUE THREAD

**Issue by StSav012** [pyqtgraph/pyqtgraph#2679] opened 2023-04-07 11:06 UTC
### Short description

`TypeError: GraphicsWidgetAnchor.__init__() takes 1 positional argument but 2 were given` appears on `PySide6>=6.5.0` when `LabelItem` gets initialized.

`PySide6<6.5.0` doesn't produce the error.

### Code to reproduce

```python
import pyqtgraph
pyqtgraph.plot()
```

To get closer to the source, run
```python
from pyqtgraph import LabelItem
LabelItem()
```

### Expected behavior

The script works fine and without an error.

### Real behavior

```plaintext
Traceback (most recent call last):
  File "issue-2679.py", line 4, in <module>
    pyqtgraph.plot()
  File "venv/lib64/python3.11/site-packages/pyqtgraph/__init__.py", line 388, in plot
    w = PlotWidget(**pwArgs)
        ^^^^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/pyqtgraph/widgets/PlotWidget.py", line 55, in __init__
    self.plotItem = PlotItem(**kargs)
                    ^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 154, in __init__
    self.titleLabel = LabelItem('', size='11pt', parent=self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib64/python3.11/site-packages/pyqtgraph/graphicsItems/LabelItem.py", line 19, in __init__
    GraphicsWidget.__init__(self, parent)
  File "venv/lib64/python3.11/site-packages/pyqtgraph/graphicsItems/GraphicsWidget.py", line 18, in __init__
    QtWidgets.QGraphicsWidget.__init__(self, *args, **kwargs)
TypeError: GraphicsWidgetAnchor.__init__() takes 1 positional argument but 2 were given
```

### Tested environment(s)

 * PyQtGraph version: `0.13.2` 
 * Qt Python binding: `PySide6 6.5.0 Qt 6.5.0` 
 * Python version: `Python 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]`
 * NumPy version: `1.24.2` 
 * Operating system: Fedora 37, kernel `6.1.15-200.fc37.x86_64`
 * Installation method: via `pip`, in a virtual environment created by `python -m venv venv`

### Additional context

The error is confusing. The line 18 (`QtWidgets.QGraphicsWidget.__init__(self, *args, **kwargs)`) doesn't mention `GraphicsWidgetAnchor` at all. Instead, `GraphicsWidgetAnchor` comes from https://github.com/pyqtgraph/pyqtgraph/blob/08f01be743cba772ae91ef567e6db59672d38f6c/pyqtgraph/graphicsItems/LabelItem.py#L20

Overall, it looks like a bug in PySide6, but I can't reproduce the error with PySide6 built-in classes (e.g., `QGraphicsWidget()` works fine).

---

As a side note, it's unfortunate that the [Qt Bindings Test Matrix](https://github.com/pyqtgraph/pyqtgraph/tree/master#qt-bindings-test-matrix) ends on Qt 6.3 and Python 3.10.

**Comment by j9ac9k** [comment] 2023-04-07 15:02
Already fixed with #2662  ...fix will be in the next release, which we'll make after PyQt6 6.5 comes out (to make sure those bindings work).

Duplicate of #2674

**Closed by j9ac9k** 2023-04-07 15:02 UTC

**Comment by StSav012** [comment] 2023-04-12 07:26
@j9ac9k, PyQt6==6.5.0 [was released](https://www.riverbankcomputing.com/news/PyQt_v6.5.0_Released) on 10 April 2023. Any news on the new release of PyQtGraph?

**Comment by j9ac9k** [comment] 2023-04-12 14:29
> @j9ac9k, PyQt6==6.5.0 [was released](https://www.riverbankcomputing.com/news/PyQt_v6.5.0_Released) on 10 April 2023. Any news on the new release of PyQtGraph?

I'm hoping in a day or two. I have a test failure locally that does not occur in CI that needs further investigation.
