### ISSUE TITLE
About glGetString(GL_VERSION)

### ISSUE THREAD

**Issue by techjjun** [pyqtgraph/pyqtgraph#1004] opened 2019-07-26 08:39 UTC
I'm using NVIDIA xavier board installed pyqtgraph and pyqt5, qtopengl
and getting error when I run GLViewWidget.py in example folder.

I checked the GL_VERSION and it says

> glGetString(GL_VERSION) = b'OpenGL ES 3.2 NVIDIA 31.1.0

I also check with Jetson tx2 and it says 

> glGetString(GL_VERSION) = 4.6.0 NVIDIA 31.1.0

How can i change OpenGL ES to OpenGL 4.6?

 * PyQtGraph version: 0.11.0
 * Qt Python binding: 5.9.5
 * Python version: 3.6
 * NumPy version:  1.16.4
 * Operating system: Xavier Ubuntu 18.0.4
 * Installation method:

**Comment by 2xB** [comment] 2019-07-26 15:07
_Quoting myself from #993:_
PyQtGraph uses PyOpenGL and Qts QtOpenGl module. I am not aware of any possibility to constrain those libraries to using a specific OpenGL version. If someone knows or finds out more, it would be great to know!

---

Speaking of issue #993, this seems to be a duplicate of that issue?

**Closed** 2019-08-04 23:14 UTC
Labels: duplicate
