### ISSUE TITLE
pyqtgraph ErrorBarItem doesn't draw a vertical line connecting horizontal error bars

### ISSUE THREAD

**Issue by adar-d** [pyqtgraph/pyqtgraph#1457] opened 2020-11-25 06:49 UTC
pyqtgraph ErrorBarItem doesn't draw a vertical line connecting horizontal error bars

### Code to reproduce
```
import pyqtgraph as pg
from pyqtgraph.Qt import QtGui, QtCore
import numpy as np

pg.setConfigOptions(antialias=True)

yPoints = np.array([4.2315e-12, 5.0400e-12, 4.7119e-12, 5.0892e-12,])
xPoints = np.array([1, 2, 3, 4])
errors = np.array([2.9131e-13, 3.452e-13, 3.3071e-13, 3.762e-13 + 3e-13])

plt = pg.plot()
errorBarItem = pg.ErrorBarItem(x=xPoints, y=yPoints,  top=errors, bottom=errors, beam=0.2)
plt.addItem(errorBarItem)
plt.plot(xPoints, yPoints, symbol='o', pen={'color': 0.8, 'width': 2})

## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
  import sys
  if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
    QtGui.QApplication.instance().exec_()

```

### Expected behavior
I would expect vertical line connecting horizontal bars to be drawn, always

### Real behavior
![Capture](https://user-images.githubusercontent.com/49107412/100191797-0e7cfb80-2ef1-11eb-8d1b-bcc410ba8413.PNG)

### Tested environment(s)
 * PyQtGraph version: 0.10.0
 * Qt Python binding: PyQt4-4.11.4
 * Python version: 3.7.7
 * NumPy version: 1.19.1
 * Operating system: win10 64 bits
 * Installation method: pip

**Comment by j9ac9k** [comment] 2020-11-26 02:18
hi @adar-d 0.10.0 is quite an old release, would you mind trying 0.11.0?  Alternatively if that doesn'tw ork, would you mind trying from the master branch?

**Comment by j9ac9k** [comment] 2020-11-26 02:53
I can replicate this on pyqt5-conda builds but not pyside2-conda builds (as well as Qt4 builds); meaning this issue was likely resolved within Qt land between Qt 5.9 and 5.12....

**Comment by j9ac9k** [comment] 2020-11-26 06:53
I reworked your example, and while I'm not sure what's wrong in the code, I can say this only becomes an issue when you make the numbers really small

```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtGui, QtCore
import numpy as np

app = pg.mkQApp()

scale = 1e-13
x = np.arange(10)
y = np.arange(10) %3 * scale
top = np.linspace(1.0, 3.0, 10) * scale
bottom = np.linspace(2, 0.5, 10) * scale

pltWidget = pg.PlotWidget()
errorBarItem = pg.ErrorBarItem(x=x, y=y,  top=top, bottom=bottom, beam=0.2)
pltWidget.addItem(errorBarItem)
pltWidget.plot(x, y, symbol='o', pen={'color': 0.8, 'width': 2})
pltWidget.show()
## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
  import sys
  if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
    QtGui.QApplication.instance().exec_()
```

with `scale = 1e-13` I get the following output:

![image](https://user-images.githubusercontent.com/646398/100317254-e6cd7800-2f70-11eb-8a96-6cad45fe79f0.png)

with `scale = 1e-12` I get the following output:

![image](https://user-images.githubusercontent.com/646398/100317323-01075600-2f71-11eb-81b2-099f4366d9ae.png)

As you're using a pretty old version of Qt, I would advise migrating to a currently supported version of Qt (5.12+).

**Comment by j9ac9k** [comment] 2020-11-26 06:56
I'm going to close this as a duplicate of #1149

**Closed by j9ac9k** 2020-11-26 06:56 UTC
