### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by sarbabi** [pyqtgraph/pyqtgraph#913] opened 2019-06-07 18:22 UTC
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-d8d6ec1d9d2a> in <module>
----> 1 pg.isosurface(my_array, 0.5)

c:\python\lib\site-packages\pyqtgraph\functions.py in isosurface(data, level)
   2067             faceTableI = np.zeros((len(triTable), i*3), dtype=np.ubyte)
   2068             faceTableInds = np.argwhere(nTableFaces == i)
-> 2069             faceTableI[faceTableInds[:,0]] = np.array([triTable[j] for j in faceTableInds])
   2070             faceTableI = faceTableI.reshape((len(triTable), i, 3))
   2071             faceShiftTables.append(edgeShifts[faceTableI])

c:\python\lib\site-packages\pyqtgraph\functions.py in <listcomp>(.0)
   2067             faceTableI = np.zeros((len(triTable), i*3), dtype=np.ubyte)
   2068             faceTableInds = np.argwhere(nTableFaces == i)
-> 2069             faceTableI[faceTableInds[:,0]] = np.array([triTable[j] for j in faceTableInds])
   2070             faceTableI = faceTableI.reshape((len(triTable), i, 3))
   2071             faceShiftTables.append(edgeShifts[faceTableI])

TypeError: only integer scalar arrays can be converted to a scalar index

my code is like this:
`
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

pg.isosurface(my_array, 0.5)
`

**Comment by ixjlyons** [comment] 2019-06-07 19:56
Looks like a duplicate of #490

**Closed by ixjlyons** 2019-06-07 19:56 UTC
Labels: duplicate

**Comment by sarbabi** [comment] 2019-06-07 19:57
yes it is duplicate but still not resolved. so why are you closing it??

**Comment by ixjlyons** [comment] 2019-06-07 19:58
Because that issue is still open, so we can keep the discussion there rather than two different issues.
