### ISSUE TITLE
Is "GraphicsItemFlag.ItemIgnoresTransformations" necessary for LegendItem

### ISSUE THREAD

**Issue by leo603222** [pyqtgraph/pyqtgraph#2028] opened 2021-10-19 09:48 UTC
In __init__ function of LegendItem, the flag "GraphicsItemFlag.ItemIgnoresTransformations" is enabled.
This flag will case wrong size of legend when exportting to image with large size.
```python
def __init__(self, size=None, offset=None, horSpacing=25, verSpacing=0,
                 pen=None, brush=None, labelTextColor=None, frame=True,
                 labelTextSize='9pt', colCount=1, sampleType=None, **kwargs):
        GraphicsWidget.__init__(self)
        GraphicsWidgetAnchor.__init__(self)
        self.setFlag(self.GraphicsItemFlag.ItemIgnoresTransformations)
```
If delete `self.setFlag(self.GraphicsItemFlag.ItemIgnoresTransformations)`, everything works fine still, and the export to image bug is fixed too.
So how self.GraphicsItemFlag.ItemIgnoresTransformations works here?
### Short description

Is "GraphicsItemFlag.ItemIgnoresTransformations" flag necessary for LegenItem?
### Code to correct

```python
def __init__(self, size=None, offset=None, horSpacing=25, verSpacing=0,
                 pen=None, brush=None, labelTextColor=None, frame=True,
                 labelTextSize='9pt', colCount=1, sampleType=None, **kwargs):
        GraphicsWidget.__init__(self)
        GraphicsWidgetAnchor.__init__(self)
        # self.setFlag(self.GraphicsItemFlag.ItemIgnoresTransformations)
```

### Expected behavior

![test](https://user-images.githubusercontent.com/92384524/137885133-6cabdc73-04ad-4340-812d-0ed7ad4fe4f0.png)
### Real behavior

![test](https://user-images.githubusercontent.com/92384524/137885275-d4ac5004-111d-4983-b5f9-321946fe4ac8.png)
When set large export image size, the legenditem is very small.

### Tested environment(s)

 * PyQtGraph version: 0.12.3
 * Qt Python binding: PyQt6.2
 * Python version:  3.9.7
 * NumPy version: 1.21.2
 * Operating system: Windows10
 * Installation method: Conda

**Comment by j9ac9k** [comment] 2021-10-21 04:51
Thanks for linking the issues @pijyoi I just looked at the git history, and noted that option was set back in the initial creation of LegendItem, and then when looking at the linked issues, I see I said the same thing.

I'm going to close this issue as a duplicate of #1552 but I can't think of a good reason to keep that flag, so I'm good with getting rid of it.

**Closed as completed by j9ac9k** 2021-10-21 04:51 UTC
