### ISSUE TITLE
ImageItem forced autoDownsample for images with dimension > 2**15

### ISSUE THREAD

**Issue by adamananos** [pyqtgraph/pyqtgraph#834] opened 2019-02-27 21:14 UTC
I find that the default turning on of autoDownsample (ImageItem.py line 247-249) for images with dimensions >2**15 drastically decreases the performance of zooming and panning. It appears the downsampling function is requiring more computation than just displaying the image. Commenting out these lines provides normal performance for zooming and panning. 

Is there a reason for the hard limit on image size for turning on autoDownsample?

**Comment by ChristophRose** [comment] 2019-03-09 22:44
I wrote about this in Issue #752 and posted a fix (or at least an improvement) in Pull Request #755.

The problem is that the entire image is downsampled every time anything is changed (even panning, which doesn't change the downsampling factor). In the Pull Request, I changed it so that downsampling is only redone when the downsampling factor changes. Zooming in and out can still slow down with very large images, but panning is no problem at all.

**Comment by j9ac9k** [comment] 2020-05-31 05:31
Fixed with #755 being merged

**Closed by j9ac9k** 2020-05-31 05:31 UTC
