### ISSUE TITLE
Add support for Qt5

### ISSUE THREAD

**Issue by mfitzp** [pyqtgraph/pyqtgraph#33] opened 2014-02-12 00:21 UTC
Are there any plans to add support for PyQt5?

I see you've got a nice wrapper around the Qt imports to support PySide/PyQt4. I had hoped that would mean a simple copy-pasta PyQt4 > PyQt5 but unfortunately you get hit with errors elsewhere (QApplication now being in QWidgets for example).

I can have a go at creating a PyQt5 fork in a branch and see how much I have to mangle it before it works, but I wanted to check nobody else was doing this first.

**Comment by kernc** [comment] 2015-06-23 19:45
What is not working yet and what more needs to be done?

**Comment by nevion** [comment] 2015-07-02 19:59
bump for some clarification of remaining work - qt5 support is getting to be quite important

**Comment by stonebig** [comment] 2015-07-14 18:48
+1

**Comment by stonebig** [comment] 2015-07-19 18:08
For information, PyQt 5.5 is just out:
- QtWebEngine based on Chromium 40
-  OpenGL 2, 3, 4 and OpenGL ES 2 and ES 3 

https://wiki.qt.io/New_Features_in_Qt_5.5

**Comment by mniethammer** [comment] 2016-05-01 15:37
What's the status on this?

**Comment by stonebig** [comment] 2016-05-01 18:12
Last Time I checked, pyqtgraph master was working well with PyQt5.6.0 (on windows)

**Comment by mniethammer** [comment] 2016-05-01 18:34
That sounds promising. Which version are you using? 

At the moment I don't see any PyQt5 related stuff in the master branch.
https://github.com/mfitzp/pyqtgraph/blob/master/pyqtgraph/Qt.py

Also a grep doesn't find any PyQt5 in the master source.

There is the automatic switcher in a three year old branch PyQt5:
https://github.com/mfitzp/pyqtgraph/blob/pyqt5/pyqtgraph/Qt.py

Current release is 0.9.1, in arch Linux automatically loading pyqt4 and not checking for pyqt5 beeing loaded.

How did you make it use PyQt5 and not complain about QObject already beeing wrapped?

**Comment by stonebig** [comment] 2016-05-01 18:37
it's in the master branch since a long time. see https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/Qt.py

**Comment by mniethammer** [comment] 2016-05-01 18:45
I see, got it working, got confused as you refer to the develop branch as master.

Then probably this issue can be closed as it's already implemented and will be available in the next release.

**Comment by georgesk** [comment] 2016-06-15 15:10
Hello, the support for QtWebKit has been dropped in Qt4 for one month (see: https://wiki.debian.org/Qt4WebKitRemoval), and there are now quite a few Debian packages which suffer from that issue. The solution is to switch to Qt5.

Please, dear Campagnola, is the "develop" branch mature enough to be published? I am currently working on a debian package, which can be migrated rather easily to use PyQt5, and which would depend on the "develop" branch of pyQtGraph (see: https://github.com/jithinbp/SEELablet-apps/tree/qt5/dependencies).

I saw that the gap between branches "master" and "develop" has widened a lot: **the diff weighs ten thousand lines**, so merging requests a big amount of work. 

Is there something wich I can do to help in this matter? 

* for example, creating an intermediate branch which contains every harmless differences which can be merged into "master" without changing its behavior, like the numerous whitespace-only changes?

**Comment by campagnola** [comment] 2016-06-16 01:55
Merging these changes to master will be trivial because that branch is only used to hold the latest release. The issues that are currently holding up release can be seen here:
https://github.com/pyqtgraph/pyqtgraph/milestones/0.9.11
My PR #349 is directly related to these, and there are a couple more to follow.

**Comment by jaxankey** [comment] 2016-10-26 15:19
Note that as of about September 23rd, the Anaconda distribution (the only way I've found to reliably install all the right scientific packages on all platforms) has switched from pyqt4 to pyqt5. Since then, installing pyqtgraph (through their installer or other means) breaks everything using pyqt (e.g. spyder and its qtconsole stop launching). 

Would be great to roll some kind of version checking during import out, so either pyqt version will work.

**Comment by campagnola** [comment] 2016-10-26 21:18
Thanks Jack, I just noticed this a few days ago.
Pyqtgraph does automatically decide which pyqt library to import. This
should start working again as soon as 0.10.0 is released (we are currently
testing release packages).

**Comment by pedromorgan** [comment] 2016-10-26 22:06
Here is the snags folks, the way i see it as using pyqt as day job..

First history is that PyQt4 are bindings from c++ code to the python2.+ interperator

so pyqt4 =
- upstream stable Qt4 "framework/platform" written in c++ 
- PyQt4 are the python2.x bindings sponsored and maintained by riverbank 
- also along later came pyside = another binding sponsered by ?

so the clever part in Pyqtgraph
is the `Qt.py` file.. and really a cool way
to import a namespace..
and in the last few years circa 2014 ish
would import either..
- the python2 + qt4 = pqtqy4
- or pyside and qt4
- or python3 and qt4 ,,\
- ie a mish mash of all

Then twooo things happened, as planned
- Qt5 was launched, and solved a few probplems..
- out came python3 and next verison = py3.qt5

so riverbank  created
py3-qt5 bindings...

At the end of the day I would recommend splitting both ie
py2-qt4=pyqtgraph4
py3-qt5=py3qt5graph

Whichever way.. the Qt.py hack to rename space a hack is the worst and best together,..
https://github.com/pyqtgraph/pyqtgraph/blame/develop/pyqtgraph/Qt.py

One thing is that we need the split folks and can volunteer..

**Comment by jaxankey** [comment] 2016-10-27 15:41
Good to know, and thanks for the reply! Will Anaconda know not to try and
download / compile / link pyqt4 if we install through their interface?

**Comment by campagnola** [comment] 2016-10-28 04:25
On Wed, Oct 26, 2016 at 3:06 PM, Pete Morgan <notifications@github.com>
wrote:

> At the end of the day I would recommend splitting both ie
>
> py2-qt4=pyqtgraph4
> py3-qt5=py3qt5graph
>
Why would you recommend that? The Qt.py hack is working pretty well so
far--we currently support Python2/3 and PyQt4/PySide/PyQt5 seamlessly
(mostly because the differences between all of these are pretty minimal).
There is also a PySide2 PR ready for review.


Luke

**Comment by onlyjus** [comment] 2016-11-02 01:03
FYI, the spyder developers have created qtpy, py2/py3/qt4/qt5... switcher,
using qt5 syntax:
https://github.com/spyder-ide/qtpy/tree/master/qtpy

You can pip install and I think it is in anaconda now too!

**Comment by brylie** [comment] 2017-08-16 09:39
Has this issue been adequately resolved? If so, consider noting the resolution and closing.

I am doing research regarding a [proposal in another project](https://github.com/cbrnr/mnelab/issues/7), and would like to make sure there are little or no issues with PyQt5 compatibility.

**Comment by brylie** [comment] 2017-08-16 09:40
Related issues:
- https://github.com/pyqtgraph/pyqtgraph/issues/434
- https://github.com/pyqtgraph/pyqtgraph/issues/488

**Comment by jaxankey** [comment] 2017-08-16 19:39
I have been using pyqtgraph in my qt5 environment since pyqtgraph 0.10 came out. It's been flawless, so much so that'd I've often wished they'd turn their wrapper into a package of its own (universal Qt4 API for Qt4 or Qt5). Can probably be closed?

**Comment by ixjlyons** [comment] 2017-08-16 20:06
@jaxankey agreed and FYI there is [https://github.com/spyder-ide/qtpy](qtpy) from the Spyder folks. I haven't tried it out in quite some time and it looks somewhat active over the last year or so. It is a Qt5-like interface to Qt4/PySide, so the converse of what you mentioned, however.

**Comment by jaxankey** [comment] 2017-08-16 20:12
Precisely why I don't use it. All my code is in PyQt4-style. :)

**Comment by brylie** [comment] 2017-08-17 08:46
Well, it seems like supporting Qt5 would imply more than using a Qt4 API in a Qt5 environment. I think one goal of 'supporting Qt5' would be to use the Qt5 APIs.

**Comment by wavexx** [comment] 2017-08-17 11:06
On Thu, Aug 17 2017, Brylie Christopher Oxley wrote:
> Well, it seems like supporting Qt5 would imply more than using a Qt4
> API in a Qt5 environment. I think one goal of 'supporting Qt5' would
> be to use the Qt5 APIs.

Does it really matter what shims are being used inside?

Where I support both PyQT4/PyQT5, I'm also using internal shims, and it
doesn't really matter.

Also, for most programs I wrote I'm also sticking to QT4 for the time
being. Although the PyQT5/QT5 api has polished some edges, I don't like
the direction QT5 has taken with QML (QML programs just suck on any
device, *especially* on the desktop).

**Comment by brylie** [comment] 2017-08-17 11:53
Does the current 'Qt5 support' still require that Qt4 is installed? I am just wondering, since I have had problems maintaining two versions of the Qt libraries. Specifically, we had a [discussion/bug related to migrating Orange3 from Qt4 to Qt5](https://github.com/biolab/orange3/issues/1613), so that it could be included by default in Anaconda navigator.

**Comment by jaxankey** [comment] 2017-08-17 14:02
I do not have Qt4 installed on any of my systems (I also use Anaconda), and
it works great.

**Comment by pedromorgan** [comment] 2017-08-17 14:35
ragardless of all the argumens above..
the position check is that..

1) py3+qt5 = future
2) py2+qt4  = legacy..

We dont wannt a break a project..
and indeed my hat off to the `import Qt.py` hack..
a source of admiration, until some ....

However we have to make a decisions..
and as i pointed out before..
we may need to branch off..
and some backports..
but hey.. its 2020 soon ??

Snag is that we can thank QT.. say again QT.. for being a cool platform..
but.. ...

**Comment by pedromorgan** [comment] 2017-08-17 14:46
but at the same time.. hats off to Qt.py ;-))

**Comment by goetzc** [comment] 2017-08-17 15:12
Debian has plans to [drop Qt 4](https://lists.debian.org/debian-devel-announce/2017/08/msg00006.html) from the next release and [Python 2 will reach EOL](https://pythonclock.org/) in two and a half years.

**Comment by campagnola** [comment] 2017-08-17 16:01
On Thu, Aug 17, 2017 at 8:10 AM, Pete Morgan <notifications@github.com>
wrote:

> However we have to make a decisions..
>
Can you clarify what decisions need to be made? Pyqtgraph supports PyQt4,
PySide, PyQt5, Python 2, and Python 3, in any combination. What more do we
need (besides PySide2 support) ? When Python 2 and Qt4 disappear
completely, pyqtgraph will still function exactly as it is.

Is the Qt.py shim approach holding us back in some way? If we really wanted
to transition pyqtgraph's internal code to using a Qt5-like API, then we
could easily add a Qt5.py and switch to that. The APIs are so similar that
I don't think it would be much work (and at the same time I'm not sure the
transition would offer much benefit).

**Comment by jaxankey** [comment] 2017-08-17 18:14
If you ever decide to switch to Qt5's API, please leave the Qt4 API present
as well (maybe as an import option). I've got a lab to run and can't spend
a month re-coding all my acquisition software. ;)

**Comment by campagnola** [comment] 2017-08-17 19:47
On Thu, Aug 17, 2017 at 11:14 AM, Jack Sankey <notifications@github.com>
wrote:

> If you ever decide to switch to Qt5's API, please leave the Qt4 API present
> as well (maybe as an import option). I've got a lab to run and can't spend
> a month re-coding all my acquisition software. ;)
>

Not to worry, Jack. We're all in the same boat; long-term stability is a
requirement for pyqtgraph.
If we did add a Qt5.py shim, then the original Qt.py would remain in place
and pyqtgraph's API should be unaffected.

**Comment by jaxankey** [comment] 2017-08-17 20:52
Awesome. Good to know! This thing is running my lab.

**Comment by dpizetta** [comment] 2018-01-19 18:42
Hi, why not use the approach of QtPy? You can choose which API to use setting a environment variable. I think your Qt.py should have the same ideas. 

https://github.com/spyder-ide/qtpy

Of course, if pyqtgraph's code is using PyQt4/PySide naming, it will be necessary to change to PyQt5/PySide2. For a long term may this would be a better option.

**Comment by j9ac9k** [comment] 2019-06-07 15:52
@dpizetta We're aware of qtpy and qt.py, and may implement it in future versions, however those projects have a much broader aim than what pyqtgraph offers.  What is more likely is that future versions may drop Qt4 support (but this won't happen for a while).

As we've implemented Qt5 compatibility, I'm going to close out this issue.

**Closed by j9ac9k** 2019-06-07 15:52 UTC

**Comment by goetzc** [comment] 2019-06-07 16:03
@j9ac9k It looks like 0.10 from 2016 is the latest release. Do you plan on pushing a new stable or development release which includes support for Qt5? 

Otherwise not many distros will package from master/develop branches, like Debian's Sid rolling development version (latest stuff) which includes [version 0.10](https://packages.debian.org/sid/python-pyqtgraph).

**Comment by j9ac9k** [comment] 2019-06-07 16:09
Development effort has picked up on pyqtgraph recently, as you can see from the "insights" button the repo page.  The overall effort is being placed into getting the next stable release out.  Version 0.10 I believe supports PyQt5 (but not PySide2).

Our main areas of focus are getting our test suite to pass for all our tested configurations (on azure-pipelines we have 18 configurations we test!).  Once we get there, evaluating other PRs should become easier as we should have more confidence that a given PR won't break things.

In the meantime, while not an ideal solution, I would consider using pyqtgraph straight from the development branch for your use case (It's what I'm doing with my projects)  You can install from the develop branch with the following command

```
pip install git+https://github.com/pyqtgraph/pyqtgraph.git@develop
```

If you want to contribute toward getting a stable release out faster, I would consider submitting PRs addressing some of the failures that we see on our [CI](https://dev.azure.com/pyqtgraph/pyqtgraph/_build/results?buildId=111).  Many of those failures can be reproduced locally as well.  Specific issues can be found on our issue board with the prefix `[CI-Fail]`.

**Comment by dpizetta** [comment] 2019-06-07 17:46
Hi, TKS. May I could help to implement a version using qtpy, I've some experience with it.

**Comment by j9ac9k** [comment] 2019-06-07 17:54
Personally, I would love to integrate `qtpy` (we would need some upstream changes to qtpy) and `pytest-qt`, however the lack of these packages aren't currently holding things up presently; our `test_Qt.py` file is passing all tests (although I have some suspicion regarding some of the mouse methods in `ui_testing.py`.

Also, we would need buy in from the rest of the team, and given the road-blocks currently facing this project, integrating qtpy isn't on our immediate priority list.

That said, if you would like to make a PR with integrating it, we would definitely review it, and I'll advocate for implementing it.
