### ISSUE TITLE
MatplotlibWidget is not compatiable with QWidget

### ISSUE THREAD

**Issue by haiiliin** [pyqtgraph/pyqtgraph#2364] opened 2022-07-14 13:55 UTC
### Short description

The MatplotlibWidget's signature is not compatiable with QWidget

### Code to reproduce

I am not quite sure about this, but I think the `MatplotlibWidget` class is not compatiable with the QWidget class. 
The MatplotlibWidget's __init__ signature:
```python
# MatplotlibWidget
def __init__(self, size=(5.0, 4.0), dpi=100):
    ...
```
But the QWidget's __init__ signature is like this:

```python
# QWidget
def __init__(self, parent=None, flags=None):
    ...
```

When I use pyuic5 to convert the .ui file to Python source that includes the custom `MatplotlibWidget` class, the generated code always assumes that the first argument is its parent, I have to modify the code every time I generate it, or I have to just use my own MatplotlibWidget class. 

### Expected behavior

Make the Matplotlibwidget compatiable with QWidget.

### Real behavior

The Matplotlibwidget is not compatiable with QWidget. 

The generated code by pyuic5 is usually like this: 

```python
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        ...
        # Something like this
        self.widget = MatplotlibWidget(self.centralwidget)
        ...

from pyqtgraph.widgets.MatplotlibWidget import MatplotlibWidget
```

### Possible solutions

According to Qt conventions, we could define the following two overloaded methods:

```python
from typing import overload

@overload
def __init__(self, size=(5.0, 4.0), dpi=100， parent=None):
    ...

@overload
def __init__(self, parent=None):
    ...
```

### Tested environment(s)

 * PyQtGraph version: 0.12.4
 * Qt Python binding: 5.15.2 
 * Python version: 3.9.12
 * NumPy version: 1.22.4
 * Operating system: Windows 10
 * Installation method: pip

**Comment by Dolphindalt** [comment] 2022-07-19 05:40
I threw up a pull request to address this issue. 

It was hard to decide how to handle dealing with the multiple constructors. I have elected to use one constructor in the pull request that has the following signature:

```python
def __init__(self, parent=None, flags=None, size=(5.0, 4.0), dpi=100):
    QtWidgets.QWidget.__init__(self, parent=parent, flags=flags)
    ...
```

There is a small dilemma that must be addressed in the design of this fix. The core of the problem is that pyuic5 is expecting the MatplotlibWidget to consume the parent as the first parameter of the constructor. This is contrary to what the author of MatplotlibWidget had likely intended; that the MatplotlibWidget constructor emulate the constructor format of Matplotlib. Rather than having two constructors, I decided that it would be better to change MatplotlibWidget so that it more closely follows the conventions of this library by accepting the parent argument first and then the additional Matplotlib related arguments. The rationale behind this decision is that this library should follow its own conventions rather than the conventions of Matplotlib.

This may not be the best approach, but I deemed it cleaner than having two constructors and some intermediary method to support both parent and size being default arguments depending on the arguments provided to the constructor. Any thoughts on this before it is merged?

**Comment by pijyoi** [comment] 2022-07-19 07:41
I am not quite sure I understand the use-case here.
You are embedding `MatplotlibWidget` in your application. Presumably, you are plotting your data without involving `pyqtgraph`.
So why not make a (modified) copy of `MatplotlibWidget.py` and ditch the `pyqtgraph` dependency altogether?

**Comment by Dolphindalt** [comment] 2022-07-19 07:48
> So why not make a (modified) copy of `MatplotlibWidget.py` and ditch the `pyqtgraph` dependency altogether?

Would this approach be indicative of the removal of `MatplotlibWidget.py`?

**Comment by haiiliin** [comment] 2022-07-19 07:52
> I am not quite sure I understand the use-case here. You are embedding `MatplotlibWidget` in your application. Presumably, you are plotting your data without involving `pyqtgraph`. So why not make a (modified) copy of `MatplotlibWidget.py` and ditch the `pyqtgraph` dependency altogether?

Actually, that's what I do at present, I just find this issue and hope to make an improvement to this library.

**Comment by haiiliin** [comment] 2022-07-19 07:59
> I threw up a pull request to address this issue.
> 
> It was hard to decide how to handle dealing with the multiple constructors. I have elected to use one constructor in the pull request that has the following signature:
> 
> ```python
> def __init__(self, parent=None, flags=None, size=(5.0, 4.0), dpi=100):
>     QtWidgets.QWidget.__init__(self, parent=parent, flags=flags)
>     ...
> ```
> 
> There is a small dilemma that must be addressed in the design of this fix. The core of the problem is that pyuic5 is expecting the MatplotlibWidget to consume the parent as the first parameter of the constructor. This is contrary to what the author of MatplotlibWidget had likely intended; that the MatplotlibWidget constructor emulate the constructor format of Matplotlib. Rather than having two constructors, I decided that it would be better to change MatplotlibWidget so that it more closely follows the conventions of this library by accepting the parent argument first and then the additional Matplotlib related arguments. The rationale behind this decision is that this library should follow its own conventions rather than the conventions of Matplotlib.
> 
> This may not be the best approach, but I deemed it cleaner than having two constructors and some intermediary method to support both parent and size being default arguments depending on the arguments provided to the constructor. Any thoughts on this before it is merged?



> I threw up a pull request to address this issue.
> 
> It was hard to decide how to handle dealing with the multiple constructors. I have elected to use one constructor in the pull request that has the following signature:
> 
> ```python
> def __init__(self, parent=None, flags=None, size=(5.0, 4.0), dpi=100):
>     QtWidgets.QWidget.__init__(self, parent=parent, flags=flags)
>     ...
> ```
> 
> There is a small dilemma that must be addressed in the design of this fix. The core of the problem is that pyuic5 is expecting the MatplotlibWidget to consume the parent as the first parameter of the constructor. This is contrary to what the author of MatplotlibWidget had likely intended; that the MatplotlibWidget constructor emulate the constructor format of Matplotlib. Rather than having two constructors, I decided that it would be better to change MatplotlibWidget so that it more closely follows the conventions of this library by accepting the parent argument first and then the additional Matplotlib related arguments. The rationale behind this decision is that this library should follow its own conventions rather than the conventions of Matplotlib.
> 
> This may not be the best approach, but I deemed it cleaner than having two constructors and some intermediary method to support both parent and size being default arguments depending on the arguments provided to the constructor. Any thoughts on this before it is merged?


I have a solution to make two constructors:

```python
from PyQt5 import QtWidgets
import typing


class MatplotlibWidget(QtWidgets.QWidget):

    @typing.overload
    def __init__(self, figsize=(6, 4), dpi=100, parent=None, flags=None):
        pass

    @typing.overload
    def __init__(self, parent=None, flags=None):
        pass

    def __init__(self, *args, **kwargs):
        if (
            (args and not isinstance(args[0], QtWidgets.QWidget))  # figsize is provided in the positional args
            or
            (kwargs and ("figsize" in kwargs or "dpi" in kwargs))  # figsize are provided in keyword args
        ):  # If figsize or dpi are provided
            figsize = args[0] if len(args) > 0 else kwargs.get("figsize", (6, 4))
            dpi = args[1] if len(args) > 1 else kwargs.get("dpi", 100)
            parent = args[2] if len(args) > 2 else kwargs.get("parent", None)
            flags = args[3] if len(args) > 3 else kwargs.get("flags", None)
        else:
            figsize = (6, 4)
            dpi = 100
            parent = args[0] if len(args) > 0 else kwargs.get("parent", None)
            flags = args[1] if len(args) > 1 else kwargs.get("flags", None)
        super().__init__(parent, flags)
        self.figsize = figsize
        self.dpi = dpi
```

**Comment by Dolphindalt** [comment] 2022-07-19 08:07
> > I threw up a pull request to address this issue.
> > It was hard to decide how to handle dealing with the multiple constructors. I have elected to use one constructor in the pull request that has the following signature:
> > ```python
> > def __init__(self, parent=None, flags=None, size=(5.0, 4.0), dpi=100):
> >     QtWidgets.QWidget.__init__(self, parent=parent, flags=flags)
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There is a small dilemma that must be addressed in the design of this fix. The core of the problem is that pyuic5 is expecting the MatplotlibWidget to consume the parent as the first parameter of the constructor. This is contrary to what the author of MatplotlibWidget had likely intended; that the MatplotlibWidget constructor emulate the constructor format of Matplotlib. Rather than having two constructors, I decided that it would be better to change MatplotlibWidget so that it more closely follows the conventions of this library by accepting the parent argument first and then the additional Matplotlib related arguments. The rationale behind this decision is that this library should follow its own conventions rather than the conventions of Matplotlib.
> > This may not be the best approach, but I deemed it cleaner than having two constructors and some intermediary method to support both parent and size being default arguments depending on the arguments provided to the constructor. Any thoughts on this before it is merged?
> 
> > I threw up a pull request to address this issue.
> > It was hard to decide how to handle dealing with the multiple constructors. I have elected to use one constructor in the pull request that has the following signature:
> > ```python
> > def __init__(self, parent=None, flags=None, size=(5.0, 4.0), dpi=100):
> >     QtWidgets.QWidget.__init__(self, parent=parent, flags=flags)
> >     ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There is a small dilemma that must be addressed in the design of this fix. The core of the problem is that pyuic5 is expecting the MatplotlibWidget to consume the parent as the first parameter of the constructor. This is contrary to what the author of MatplotlibWidget had likely intended; that the MatplotlibWidget constructor emulate the constructor format of Matplotlib. Rather than having two constructors, I decided that it would be better to change MatplotlibWidget so that it more closely follows the conventions of this library by accepting the parent argument first and then the additional Matplotlib related arguments. The rationale behind this decision is that this library should follow its own conventions rather than the conventions of Matplotlib.
> > This may not be the best approach, but I deemed it cleaner than having two constructors and some intermediary method to support both parent and size being default arguments depending on the arguments provided to the constructor. Any thoughts on this before it is merged?
> 
> I have a solution to make two constructors:
> 
> ```python
> from PyQt5 import QtWidgets
> import typing
> 
> 
> class MatplotlibWidget(QtWidgets.QWidget):
> 
>     @typing.overload
>     def __init__(self, figsize=(5.0, 4.0), dpi=100, parent=None, flags=None):
>         pass
> 
>     @typing.overload
>     def __init__(self, parent=None, flags=None):
>         pass
> 
>     def __init__(self, *args, **kwargs):
>         if (
>             (args and not isinstance(args[0], QtWidgets.QWidget))  # figsize is provided in the positional args
>             or
>             (kwargs and ("figsize" in kwargs or "dpi" in kwargs))  # figsize or dpi are provided in keyword args
>         ):  # If figsize or dpi are provided
>             figsize = args[0] if len(args) > 0 else kwargs.get("figsize", (5.0, 4.0))
>             dpi = args[1] if len(args) > 1 else kwargs.get("dpi", 100)
>             parent = args[2] if len(args) > 2 else kwargs.get("parent", None)
>             flags = args[3] if len(args) > 3 else kwargs.get("flags", None)
>         else:
>             figsize = (5.0, 4.0)
>             dpi = 100
>             parent = args[0] if len(args) > 0 else kwargs.get("parent", None)
>             flags = args[1] if len(args) > 1 else kwargs.get("flags", None)
>         super().__init__(parent, flags)
>         self.figsize = figsize
>         self.dpi = dpi
> ```

Super elegant! I did not know you could utilize the typing hints like this!

**Closed** 2022-08-07 03:27 UTC
