### ISSUE TITLE
TypeError: GraphicsWidgetAnchor.__init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by Khanhlinhdang** [pyqtgraph/pyqtgraph#2680] opened 2023-04-07 16:56 UTC
pyqtgraph.examples.customGraphicsItem, pyqtgraph.examples.customPlot and alot examples are not working.
it show error "TypeError: GraphicsWidgetAnchor.__init__() takes 1 positional argument but 2 were given"

**Comment by j9ac9k** [comment] 2023-04-07 16:57
Duplicate of #2679 and #2674 and already fixed in #2662

**Closed by j9ac9k** 2023-04-07 16:57 UTC
