### ISSUE TITLE
console "Exceptions" layout is broken

### ISSUE THREAD

**Issue by sbourdeauducq** [pyqtgraph/pyqtgraph#197] opened 2015-07-24 12:37 UTC
See "Exception Handling" text in screenshot below.

![console_broken](https://cloud.githubusercontent.com/assets/720864/8874450/b6fefb42-3243-11e5-9613-6a9edc842c75.png)

**Comment by 2xB** [comment] 2019-06-20 00:27
I cannot reproduce this bug in pyqtgraph 0.10.0 using Qt 5.9.6. But I also cannot get the `Exceptions...` area to show anything. Exceptions like e.g.
```python3
raise ValueError()
```
only show in the console area - not shure if this is intended and if I miss something.

**Comment by sbourdeauducq** [comment] 2019-06-20 02:27
> I cannot reproduce this bug in pyqtgraph 0.10.0 using Qt 5.9.6.

I suspect it may have to do with font DPI or sizes.

**Comment by j9ac9k** [comment] 2019-06-20 03:07
Thanks for following up! Since you opened the issue, Qt has had large improvements with respect to HiDPI displays.

**Comment by j9ac9k** [comment] 2021-01-23 18:21
While working on #1509 this appears to work now, will close out this issue when the fix is merged

![image](https://user-images.githubusercontent.com/646398/105610470-900fcf00-5d64-11eb-8e24-fec29fc037f3.png)

**Closed** 2021-01-27 18:05 UTC
Labels: cannot reproduce
