### ISSUE TITLE
ScatterPlotItem right click and ScatterPlotItem(listOfPoints) no longer works between pyqtgraph 0.11 and 0.12

### ISSUE THREAD

**Issue by mesa-git** [pyqtgraph/pyqtgraph#2062] opened 2021-11-08 12:56 UTC
Hello guys,

I have upgraded to pyqtgraph 0.12 from 0.11 and i've noticed behavioral differences between versions.

```python
def plotObjects(self):
        objects= list()
        for objectId in range(OBJ_NUMBER):
                x = getX
                y = getY
		measured = getMeasured()
                if abs(x) > float(0.0) and abs(y) > float(0.0):
		obj_info = {'pos': (fus_dy, fus_dx),
                	    'size': FUS_OBJECT_SYMBOL_SIZE,
                            'symbol': FUS_OBJECT_SYMBOL,
                            'brush': pg.mkBrush(QColor(color_set['OBJ_COLOR'])),
                            'pen': pg.mkPen(QColor(color_set['OBJ_COLOR'])),
                            'data': f"FUS_{objectId}"}
                    if measured == 1:
			obj_info['brush'] = pg.mkBrush(None)

                    objects.append(obj_info)
                    # add text item that indicates object id
                    label = pg.TextItem(text=str(objectId), color=color_set['OBJ_COLOR'], anchor=([1, 1]))
                    label.setPos(x, y)
                    self.plotInstance.addItem(label)

        scatterPlotItem = pg.RightClickableScatterPlotItem(objects)
        self.plotInstance.addItem(scatterPlotItem)
        scatterPlotItem.sigClicked.connect(self.point_clicked)
```

RightClickableScatterPlotItem is below.

```python
class RightClickableScatterPlotItem(pg.ScatterPlotItem):
    sigRightClicked = pg.QtCore.Signal(object, object)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def mouseClickEvent(self, ev):
        if ev.button() == pg.QtCore.Qt.RightButton:
            pts = self.pointsAt(ev.pos())
            if len(pts) > 0:
                self.ptsClicked = pts
                ev.accept()
                self.sigRightClicked.emit(self, self.ptsClicked)
            else:
                ev.ignore()
        else:
            super().mouseClickEvent(ev)
```

This used to plot different points with their separate brushes.
But now it plots all points with the last brush used.
I've noticed this does not happen if pxMode=True but then the points look all wrong.

How do i fix this?

The second problem i've noticed is that the right-click overwrite no longer works.
That last line (scatterPlotItem.sigClicked.connect(self.point_clicked)) used to be trigger the emit to this:

```python
    def point_right_clicked(self, item, ptsClicked):
        # Assume that we click only an object once
        # e.g. there is exactly one object under our exact cursor position
        assert(len(ptsClicked) == 1)

        x_intersect = np.argwhere(item.data['x'] == ptsClicked[0].pos().x())
        y_intersect = np.argwhere(item.data['y'] == ptsClicked[0].pos().y())
        point_index = np.intersect1d(x_intersect, y_intersect)[0]

        fus_index = item.data[point_index]['data']

        selected_points = {}
        selected_points['id'] = index

        self.menu.popupWithContext(selected_points)
```

which takes the list of points that is emitted and tries to figure out which one is clicked.

Anyway now I cannot get to trigger the Right-Click on the object.
It shows the background menu.

"View All, 
Y Axis,
X Axis,
Mouse Mode
etc..."

It does work on Left-Click on the ScatterPlotItem if i replace

if ev.button() == pg.QtCore.Qt.RightButton:
        
with 

if ev.button() == pg.QtCore.Qt.LeftButton:
                
How to fix this issue?

Thanks for the help and the great work on this amazing library btw :)

**Comment by j9ac9k** [comment] 2021-11-08 16:48
Hi @gitMesa 

I edited your issue slightly so that it shows syntax highlighting in the code-blocks, this makes it a bit easier to read.

Between 0.11 and 0.12 we had a substantial overhaul of our ScatterPlotItem see https://github.com/pyqtgraph/pyqtgraph/pull/1420 which was merged in 0.11.1.

Not directly related to your issue, but related to the example you have, there is a significant performance boost from re-using brushes of the same color/features; in your example code it appears you create a number of brushes and pens that are different instances but with the same features; it would be strongly suggested you re-use as many of your QPen and QBrush objects as possible.

Would you be able to provide us with the entire contents of a file that can demonstrate the issue?  This is typically easiest done when modifying one of the examples we ship with.  Ideally this would incorporate your `plotObjects` method (or the logic within the method). 

Regarding the second issue of your signal not firing, I can't explain that, other than to suggest one of your if-statements didn't meet the criteria; to debug that, you should likely insert a `breakpoint()` statement in that method, and step through making sure you actually meet the criteria for the if-statements (is in-fact a right click and `len(pts) > 0`)

**Comment by gitMesa** [comment] 2021-11-09 06:50
Hey, Thanks for the reply.

Yesterday I spent most of the day trying to get the brushes back in order :)
The only way I managed to do it is to have each point a different ScatterPlotItem
But that's probably the slowest approach.

Maybe 3 different list of spots for the 3 different brushes I have will do the trick.
If you don't have any other faster approach.

For my app the speed is not THAT important, as long as it doesn't slow things down.
I have some video processing that slows things down much more noticeable.

Sorry i cannot post screenshots, because i cannot upload screenshots :( Company policy.
For the ScatterPlotItem right click event... I've traced it down to these lines:


Python3.9.7\Lib\site-packages\pyqtgraph\GraphicsScene\GraphicsScene.py

https://github.com/pyqtgraph/pyqtgraph/blob/13df11139556c89c19ee83fe985c235e451e7ea8/pyqtgraph/GraphicsScene/GraphicsScene.py#L332



`                for item in self.itemsNearEvent(ev):
                    if not item.isVisible() or not item.isEnabled():
                        continue
                    if hasattr(item, 'mouseClickEvent'):
                        ev.currentItem = item
                        try:
                            item.mouseClickEvent(ev)
                        except:
                            debug.printExc("Error sending click event:")
                            
                        if ev.isAccepted():
                            if item.flags() & item.GraphicsItemFlag.ItemIsFocusable:
                                item.setFocus(QtCore.Qt.FocusReason.MouseFocusReason)
                            break
`

where the self.itemsNearEvent(ev)
returns a <pyqtgraph.graphicsItems.AxisItem.AxisItem object at 0x0000026673F45310>

which calls this

https://github.com/pyqtgraph/pyqtgraph/blob/13df11139556c89c19ee83fe985c235e451e7ea8/pyqtgraph/graphicsItems/AxisItem.py#L1219

which calls this 

https://github.com/pyqtgraph/pyqtgraph/blob/13df11139556c89c19ee83fe985c235e451e7ea8/pyqtgraph/graphicsItems/ViewBox/ViewBox.py#L1256

which then automatically accepts the event, triggering the break at the end of the copied code.

I confirmed this by doing showGrid(x=False, y=False) on my pg.PlotWidget

So I think that my RightClickableScatterPlotItem is put at the end of the list returned by self.itemsNearEvent(ev), and it breaks before it reaches it.

How to fix this?

**Comment by 905132553** [comment] 2024-09-06 15:53
Hello Guys, 

Any update on the issue that right click on a item doesn't work when grid is turned on?

I just run into similar issue that the right-click overwrite no longer works. 
pg=0.13.7 python=3.11.9
Below simplified codes can reproduce the issue, when right click the target item, it shows it's own context menu, but not when plot gird is turned on:
code lines:

```
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtGui, QtWidgets

win = pg.GraphicsLayoutWidget(show=True)

p1=win.addPlot()

class myTargetItem(pg.TargetItem):
    sigEdit=QtCore.Signal(object)
    # On right-click, raise the context menu
    def mouseClickEvent(self, ev):
        if ev.button() == QtCore.Qt.MouseButton.RightButton:
            print('rb_click')
            if self.raiseContextMenu(ev):
                ev.accept()

    def raiseContextMenu(self, ev):
        menu = self.getContextMenus()
        pos = ev.screenPos()
        menu.popup(QtCore.QPoint(int(pos.x()), int(pos.y())))
        return True

    def getContextMenus(self, event=None):
            self.menu = QtWidgets.QMenu() 
            green = QtGui.QAction("Green", self.menu)
            self.menu.addAction(green)
            blue = QtGui.QAction("Blue", self.menu)
            self.menu.addAction(blue)
            return self.menu

item1=myTargetItem(pos=(0.5,0.5))
p1.addItem(item1)
# p1.showGrid(x=True, y=True)

if __name__ == '__main__':
    pg.exec()

```

**Comment by pijyoi** [comment] 2024-09-08 06:40
For whatever reason, adding `item1.setZValue(101)` makes the context menu show when the grid is enabled.
Specifically, a value of 100 does not work. I can't locate in the code where something else was set to 100.

**Comment by 905132553** [comment] 2024-09-08 13:42
Set the zvalue to 101 works. Thank you, really helpful.

**Comment by mesa-git** [comment] 2024-09-08 14:21
Good find. Something must be on top and absorb the event. At least we can check what...

**Comment by pijyoi** [comment] 2024-09-13 14:20
Alright, I found out why a `zValue` of 101 works.

An item's _effective_ `zValue` includes the `zValue` of its parent.
https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/GraphicsScene/GraphicsScene.py#L420-L429

An `AxisItem` (`zValue` 0.5) is a child of `PlotItem` (`zValue` 0.0).
The `TargetItem` (`zValue` x) is a child of `ViewBox` (`zValue` -100.0) which is itself a child of `PlotItem` (`zValue` 0.0)

So `TargetItem`'s effective `zValue` is "`x` - 100" vs `AxisItem`'s 0.5.
That's why setting a `zValue` of 100 still has it ranking behind the `AxisItem`.

**Comment by 905132553** [comment] 2024-09-13 15:20
@pijyoi thank you for figuring it out.  
Still a question though, if you change to left button click event, or middle button, then it doesn't require that high z-value, why is that?

**Comment by pijyoi** [comment] 2024-09-14 00:55
The item zValue only determines which item gets the first right of refusal in accepting the mouse click event. 

If the item does not accept it, the event is passed on to the next item, and so on. 

So in your case, the item "in front" was only accepting right clicks.

**Comment by pijyoi** [comment] 2024-09-17 12:52
I have created PR #3152 that hopefully fixes this issue.
@mesa-git and @905132553 , if you are able to, could you test out the PR to see if it fixes your problems.

**Closed** 2024-10-13 07:15 UTC
Labels: ScatterPlotItem
