### ISSUE TITLE
export image bug related to type casting

### ISSUE THREAD

**Issue by ZacDiggum** [pyqtgraph/pyqtgraph#454] opened 2017-03-03 13:50 UTC
Hi there,

I've got a Qt5-only Python distro installed (WinPython 3.5 Qt5) which includes pyqtgraph 0.10.0. Exporting images from PlotWidgets and ImageViews doesn't work anymore and gives this exception:

`Traceback (most recent call last):
  File "C:\WinPython35_Qt5\python-3.5.3.amd64\lib\site-packages\pyqtgraph\exporters\Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "C:\WinPython35_Qt5\python-3.5.3.amd64\lib\site-packages\pyqtgraph\exporters\ImageExporter.py", line 70, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
TypeError: 'float' object cannot be interpreted as an integer
QWaitCondition: Destroyed while threads are still waiting`

Didn't happen with WinPython 3.5 Qt4 (pyqtgraph 0.9.10 I think). Am I the only one experiencing this?

Update: simple fix: in ImageExporter.py, line 70:
`bg = np.empty((int(self.params['width']), int(self.params['height']), 4), dtype=np.ubyte)`

**Comment by sem-geologist** [comment] 2017-03-05 14:26
No, I got the same thing in debian testing, and I fixed it exactly same

**Comment by ZacDiggum** [comment] 2017-03-05 17:31
Hehe, I see. I made a PR: #457

**Comment by cuongtv89ks** [comment] 2017-03-07 04:52
thank you!! I fixed like your guide, but for python 2.7 although it has announced this error, it has still exported image.

**Comment by sem-geologist** [comment] 2017-03-07 08:22
The fix here is a bit a hack, the real problem is that parameter tree `param` have declared variables `height` an `width` to be integers, but are cast to float with xhnage of parameter.

**Comment by ZacDiggum** [comment] 2017-03-07 09:18
@cuongtv89ks is right. This bug is related to the latest numpy throwing an exception when using floats in np.empty(). Older versions just give a warning:
`VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future`
I wonder if there are more lines in the code like that...

**Comment by sem-geologist** [comment] 2017-03-07 10:53
numpy is right to do that, it is not the bug of numpy, the problem is `parm` outputing float somehow while it should (and is intended to) output integer.

**Comment by honkomonk** [comment] 2017-03-07 14:12
I agree with @sem-geologist. The problem is that the integer-spinbox in the parameter tree actually returns a float value (here the "width" and "height" parameters in the export dialog box).
This happens when the value is read immediately after setting a float value with .setValue(), like it happens in ImageExporter.py.

A quick fix is to cast the values explicitly to int.
See:  https://groups.google.com/forum/?nomobile=true#!topic/pyqtgraph/4jiAPUpLpF4

**Comment by ZacDiggum** [comment] 2017-03-07 18:24
I know it's not numpy's fault. Maybe my expression was a little bit misleading. Of course this is a pyqtgraph bug.
@honkomonk I just realized the post you linked is one month old and nobody bothered to fix this problem...
In my PR I put the int() casting a couple of lines further up where it looked safer to me.

**Comment by ixjlyons** [comment] 2019-05-24 05:46
This should be fixed as of #458 and #479. Feel free to re-open if you're still experiencing this issue with the latest `develop` branch.

**Closed** 2019-05-24 05:46 UTC
