### ISSUE TITLE
Possible conda requirement error for pyqtgraph=0.13.1

### ISSUE THREAD

**Issue by jdegenstein** [pyqtgraph/pyqtgraph#2458] opened 2022-10-03 16:56 UTC
Currently running into an issue when running a GH action involving pyqt and pyqtgraph. The versions in this GH action are currently unpinned and mamba/conda are both picking pyqt=5.12.3 and pyqtgraph=0.13.1. I believe pyqtgraph should require pyqt=5.15+ but there may be an issue with the conda-forge pyqtgraph package? I am not able to run the application in question because pyqtgraph complains about a too old pyqt version.
`PyInstaller\loader\pyimod03_importers.py:495: RuntimeWarning: PyQtGraph supports Qt version >= 5.15, but 5.12.9 detected.`

**Comment by j9ac9k** [comment] 2022-10-03 17:01
Looks like the [pyqtgraph-feedstock](https://github.com/conda-forge/pyqtgraph-feedstock) recipe has to be updated: 

https://github.com/conda-forge/pyqtgraph-feedstock/blob/main/recipe/meta.yaml#L18-L28

The maintainer that has been the one involved with setting that up is AFK for a bit.... 

I think pyqtgraph for the time being is compatible with 5.12 (so you shouldn't see any breakage, just that warning) but it won't stay like that for long.  That said, the conda qt bindings for 5.15 we have found to be much more robust  than their 5.12 equivalents.

I don't have merge rights to the feedstock there, but a PR to the feedstock would be much appreciated.

**Comment by j9ac9k** [comment] 2022-10-03 17:08
Looks like there is already an open PR there; should be resolved shortly!

**Comment by jdegenstein** [comment] 2022-10-03 17:12
Ok thank you very much. Glad to hear about the PR to fix this. I was seeing breakage in my application related to this, see full error dump here:
```PyInstaller\loader\pyimod03_importers.py:495: RuntimeWarning: PyQtGraph supports Qt version >= 5.15, but 5.12.9 detected.
Traceback (most recent call last):
  File "run.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cq_editor\__main__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cq_editor\main_window.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "cq_editor\widgets\viewer.py", line 32, in <module>
  File "cq_editor\widgets\viewer.py", line 36, in OCCViewer
  File "pyqtgraph\parametertree\Parameter.py", line 136, in create
  File "pyqtgraph\parametertree\Parameter.py", line 216, in __init__
  File "pyqtgraph\parametertree\Parameter.py", line 600, in addChildren
  File "pyqtgraph\parametertree\Parameter.py", line 581, in addChild
  File "pyqtgraph\parametertree\Parameter.py", line 618, in insertChild
  File "pyqtgraph\parametertree\Parameter.py", line 136, in create
  File "pyqtgraph\parametertree\parameterTypes\basetypes.py", line 280, in __init__
  File "pyqtgraph\parametertree\Parameter.py", line 219, in __init__
  File "pyqtgraph\parametertree\Parameter.py", line 312, in setValue
  File "pyqtgraph\parametertree\parameterTypes\color.py", line 23, in _interpretValue
  File "pyqtgraph\functions.py", line 272, in mkColor
ValueError: Unable to convert FF0 to QColor
[19320] Failed to execute script 'run' due to unhandled exception!```

**Comment by j9ac9k** [comment] 2022-10-03 17:16
not sure if this is related to the dependency or not, but `mkColor` does not accept hex-string color values that don't start with a `#`.  We rolled out this change some time ago;... that said this might be a bug still.

if you can do an editable install, can you insert a breakpoint [here](https://pyqtgraph.readthedocs.io/en/latest/) and query the value of `v` ? if it doesn't have a leading `#` that's likely a legit bug.

**Comment by ksunden** [comment] 2022-10-03 17:23
I've already PR'd the update for the feedstock conda-forge/pyqtgraph-feedstock#25

**Comment by ksunden** [comment] 2022-10-03 17:24
Was waiting for CI and now that it's passed, I've merged it

**Comment by j9ac9k** [comment] 2022-10-03 17:24
Thanks @ksunden !

**Comment by jdegenstein** [comment] 2022-10-03 17:27
Thanks @ksunden 

@j9ac9k the color value is listed as `'value': "FF0"`

**Comment by j9ac9k** [comment] 2022-10-03 17:29
> Thanks @ksunden
> 
> @j9ac9k the color value is listed as `'value': "FF0"`

blerg

@ntjess can you verify the color parameter tree is working as intended, by sending string hex values with a leading `#`?

**Comment by j9ac9k** [comment] 2022-10-03 20:48
> @jdegenstein is this color value in your code or pyqtgraph's? I wasn't able to find it in our code base. Recently (0.13), we no longer support making colors from strings that don't have a common interpretation (like `"r"`) unless they are prefixed with a `#` as @j9ac9k pointed out
> 
> For me, everything works as expected when calling `Parameter.create(name="test", type="color", value="#ff0")`

Oh, issue being that it was done via `Parameter.create(name="test", type="color", value="FF0")`? If that's the case, yeah that's going to break... hard to catch all use cases because we support non-hex string inputs to `mkColor` ([such as the SVG color names](https://www.w3.org/TR/SVG11/types.html#ColorKeywords))

**Comment by jdegenstein** [comment] 2022-10-03 21:00
To clarify yes, the "FF0" is in our code-base. It works fine in pyqtgraph=0.12.4 but not 0.13.1. I will try changing it and see if this prevents the crash.

**Comment by j9ac9k** [comment] 2022-10-03 21:01
> To clarify yes, the "FF0" is in our code-base. It works fine in pyqtgraph=0.12.4 but not 0.13.1. I will try changing it and see if this prevents the crash.

It should.  In our defense, we've had a deprecation dance about this as best we could!

https://github.com/pyqtgraph/pyqtgraph/blob/pyqtgraph-0.12.4/pyqtgraph/functions.py#L271-L276

**Comment by j9ac9k** [comment] 2022-10-03 21:19
Just looked on the linked PR; never have I seen CQ-editor, as a Mechanical Engineer I love that pyqtgraph is used for a project of this type.  If you ever have questions on how to potentially better integrate with pyqtgraph or get some higher performance; please reach out!

**Comment by j9ac9k** [comment] 2022-10-04 00:35
In going to close out this issue as I think everything has been resolved. 👍

**Closed** 2022-10-04 00:36 UTC
