### ISSUE TITLE
GraphicsView.py with Point TypeError related to PySide2.QtCore.QPoint

### ISSUE THREAD

**Issue by pointcloud-ai** [pyqtgraph/pyqtgraph#805] opened 2019-01-09 02:47 UTC
versions : 
numpy                         1.16.0rc2 
PyOpenGL                      3.1.0  
pyqtgraph                     0.11.0.dev0+g2e69b9c
PySide2                       5.12.0   
error :
Traceback (most recent call last):
  File "/Users/ming/pyviewer_venv/lib/python2.7/site-packages/pyqtgraph/widgets/GraphicsView.py", line 365, in mouseMoveEvent
    delta = Point(ev.pos() - self.lastMousePos)
TypeError: 'PySide2.QtCore.QPoint.__sub__' called with wrong argument types:
  PySide2.QtCore.QPoint.__sub__(Point)
Supported signatures:
  PySide2.QtCore.QPoint.__sub__(PySide2.QtCore.QPoint)

**Comment by ixjlyons** [comment] 2019-01-11 00:15
Duplicate of #799

**Comment by j9ac9k** [comment] 2019-05-23 22:48
This should have been fixed with https://github.com/pyqtgraph/pyqtgraph/pull/824 let us know if you're still experiencing this issue.

**Closed by j9ac9k** 2019-05-23 22:48 UTC
