### ISSUE TITLE
segmentation fault when importing PyQt5 modules 

### ISSUE THREAD

**Issue by liueryun** [pyqtgraph/pyqtgraph#1029] opened 2019-08-28 15:21 UTC
`from pyqtgraph.Qt import QtGui, QtCore`
`from pyqtgraph.flowchart import Flowchart`
`from PyQt5.Qt import Qt #this line causes error on the fc line`

`if __name__ == '__main__':`
`app = QtGui.QApplication([])`
`fc = Flowchart(terminals={'dataIn':{'io': 'in'}, 'dataOut': {'io': 'out'}}) # segmentation fault here!`
...

Here are additional info.:
pyqtgraph version: 0.10.0
Qt Python bingding: PyQt5 5.11.2 Qt 5.11.1
Python version: 3.7.0
Numpy version: 1.15.2
OS: Mac OS 10.14.2
Install: sudo pip3 install pyqtgraph

**Comment by 2xB** [comment] 2019-08-28 18:04
@liueryun Could you please paste the full output of the following script? And please put the output in "code fences" (they help with the readability of the log output):
````
```
log output
```
````

Script:

```python3
import pyqtgraph.Qt as pgQt
from pyqtgraph.flowchart import Flowchart

import faulthandler
faulthandler.enable()

print("a", pgQt.VERSION_INFO)

from PyQt5.Qt import Qt

print("b", pgQt.VERSION_INFO)

app = pgQt.QtGui.QApplication([])
fc = Flowchart(terminals={'dataIn':{'io': 'in'}, 'dataOut': {'io': 'out'}})
```

Thank you very much in advance.
Best regards!

**Comment by liueryun** [comment] 2019-08-29 00:19
Here are the  outputs of your script:

```
/usr/local/bin/python3.7 /Users/eryunliu/Documents/Research/Projects/Visionflow/src/visionflow.py
a PyQt5 5.11.2 Qt 5.11.1
b PyQt5 5.11.2 Qt 5.11.1
Fatal Python error: Segmentation fault

Current thread 0x000000010ac0b5c0 (most recent call first):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyqtgraph/flowchart/Terminal.py", line 277 in __init__
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyqtgraph/flowchart/Terminal.py", line 39 in __init__
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyqtgraph/flowchart/Node.py", line 148 in addTerminal
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyqtgraph/flowchart/Flowchart.py", line 114 in addTerminal
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyqtgraph/flowchart/Flowchart.py", line 82 in __init__
  File "/Users/eryunliu/Documents/Research/Projects/Visionflow/src/visionflow.py", line 31 in <module>

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

```

@2xB

**Comment by 2xB** [comment] 2019-08-29 19:14
@liueryun: I managed to reproduce this behavior without any PyQtGraph code, but could not reproduce it using PyQt 5.13.0 and sip 4.19.18. Can you verify that this error only occurs with Python 5.9?

```python3
import sys

import pyqtgraph.Qt as pgQt
from pyqtgraph.flowchart import Flowchart, Terminal, TerminalGraphicsItem, Node

import faulthandler
faulthandler.enable()

from PyQt5.Qt import Qt
from PyQt5 import QtWidgets

app = QtWidgets.QApplication([])

a = QtWidgets.QGraphicsRectItem(0, 0, 10, 10, None)
print("a", a)
b = pgQt.QtWidgets.QGraphicsRectItem(0, 0, 10, 10, None)
print("b", b)

class FakeTerm:
    def name():
        return "FakeTerm_name"

    def isRenamable():
        return False

c = TerminalGraphicsItem(FakeTerm)
print("c", c)

class FakeNode:
    def graphicsItem():
        return None 

d = Terminal(FakeNode, "terminal_name", "in")
print("d", d)

e = Node("node_name")
e.addTerminal("terminal_name2", io="in")
print("e", e)

fc = Flowchart(terminals={'dataIn':{'io': 'in'}, 'dataOut': {'io': 'out'}})
print("fc", fc)
```

outputs
```
Qt version: 5.9.6
SIP version: 4.19.8
PyQt version: 5.9.2
QApplication: invalid style override passed, ignoring it.
Segmentation fault
```
.

**Comment by 2xB** [comment] 2019-08-29 19:21
Sorry, I gave the wrong source code and asked the wrong question, I corrected both in my above post.
The problem here is that pyqtgraphs `GraphicsObject` overrides `itemChange`, and for whatever reason, the combination of purely overriding this method and passing a `GraphicsObject` as parent to a `QGraphicsRectItem` generates this segfault in the mentioned configuration.

**Comment by 2xB** [comment] 2019-08-29 19:24
Further testing shows that this is independent of the SIP version, but fixed in the latest PyQt5 version. @liueryun Sorry for the SPAM - Could you please just verify that upgrading to PyQt5 5.13.0 fixes your issue?

**Comment by liueryun** [comment] 2019-08-30 02:17
Yes! Simply upgrading to PyQt5 5.13.0 fixed my problem. Thank you very much. @2xB

**Comment by j9ac9k** [comment] 2019-08-30 13:36
@liueryun would you be good if we closed out this issue?  I'm not sure there is anything we can do to fix this on our end.  Not sure when a fix here specifically was made, hopefully one of the 5.12.x versions does not have this issue (as Qt 5.9.x, 5.12.x, 5.15.x are LTS versions).

**Closed** 2019-08-30 14:24 UTC
