### ISSUE TITLE
Some Errors in ImageView of pyqtgraph.examples 

### ISSUE THREAD

**Issue by FengZhiheng** [pyqtgraph/pyqtgraph#1290] opened 2020-07-04 07:11 UTC
### Short description

ValueError: could not broadcast input array from shape (10) into shape (100)

### Code to reproduce

```python
import pyqtgraph.examples
pyqtgraph.examples.run()
```
click ROI button

### Expected behavior

![Uploading image.png…]()

### Real behavior

```
An error occurred?
Post the full traceback inside these 'code fences'!
```

### Tested environment(s)

 * PyQtGraph version: pyqtgraph-0.11.0
 * Qt Python binding: 
 * Python version: 3.5 and 3.7
 * NumPy version: 1.18.5
 * Operating system: win10
 * Installation method:

**Comment by j9ac9k** [comment] 2020-07-04 15:20
Hi @FengZhiheng , I'm going to close this as a duplicate of #1280

Thanks for the submission!

**Closed** 2020-07-04 15:22 UTC
