### ISSUE TITLE
hoverEvent with parentItem None

### ISSUE THREAD

**Issue by georgedimitriadis** [pyqtgraph/pyqtgraph#511] opened 2017-07-13 19:04 UTC
Hello,

I am developing with python 3.5 pyqtgraph 0.10.0 on windows 10

I am making a custom ViewBox that allows PolyLineROIs to be created live through mouse clicks.

I am using this to find the points inside the ROI that are on a ScatterPlotItem. It works fine when I am adding points to the ROI.

I also want to call a function to update the point detection when I move a ROI handle.
To do this I am calling a function connected to a sigRegionChangeFinished event. Every now and then I get the following error
File "E:\InstalledSoftware\Languages\Pythons\Miniconda3_3p5\lib\site-packages\pyqtgraph\graphicsItems\ROI.py", line 2155, in hoverEvent
    |      if self.parentItem().translatable:
    |  AttributeError: 'NoneType' object has no attribute 'translatable'

It of course goes away if I add a self.parentItem() is not None in the if clause in line 2155

Also what I realized is the sigRegionChangeFinished is being called multiple times as I am dragging the handle. I was hoping it would be called only when I released it (which would make life much easier). It is not a serious problem though for what I am doing. I am just mentioning it here.

I am happy to give you more details of the code if you need to

Thanks

**Comment by j9ac9k** [comment] 2019-06-04 19:44
Closing this issue as it's a duplicate of #884 which we're diagnosing.

**Closed by j9ac9k** 2019-06-04 19:44 UTC
