### ISSUE TITLE
Wrong position of plots on second display when using different windows:"Scale and layout" settings on both displays.

### ISSUE THREAD

**Issue by hi2010** [pyqtgraph/pyqtgraph#1417] opened 2020-10-23 14:21 UTC
Hello,

i plotted some data with the following code:
`import pyqtgraph as pg
pg.plot([1,2,3,4],[3,6,4,5]) `

Using a computer with two desktops and windows 10.
On the first screen the windows setting "Scale and layout" is set to 125%, on the second screen the windows setting Scale and layout is set to 150%.

On the main screen the data is displayed right, on the second screen the data is plotted with some offset.
The offset seems visually to be the same independent of how much the plot is zoomed but the offset in axis values changes with the zoom.

Probably not relevant: main screen is full hd, second screen is 3840x2160.

### Short description
Plotting using displays with different windows setting "Scale and layout" the data gets displayed wrong on the second screen.

### Code to reproduce
```python
import pyqtgraph as pg
pg.plot([1,2,3,4],[3,6,4,5]) 
```

### Expected behavior
A plot where the line starts at x=1 y=3.

### Real behavior
A plot where the line starts somewhere else, dependant of the zoom and display.

### Tested environment(s)

 * PyQtGraph version:pyqtgraph       0.11.0
 * Qt Python binding: PyQt5.15.1
 * Python version: 3.8.6
 * NumPy version: 1.19.2
 * Operating system: windows 10
 * Installation method: pip

**Comment by ntjess** [comment] 2021-01-23 23:42
Duplicate of #1250? @j9ac9k couldn't hurt to see if your recent pr fixes this too.

**Comment by j9ac9k** [comment] 2021-01-23 23:45
I'm having trouble getting the hidpi scaling working for all conditions, but I'm not done experimenting yet.  I've got the text to not be fuzzy on all monitors but the checkboxes in the parameter tree are getting clipped when on a not hidpi display.

**Closed** 2021-01-27 18:05 UTC
Labels: hidpi
