### ISSUE TITLE
Crash displaying flat image with integer values

### ISSUE THREAD

**Issue by JPHammonds** [pyqtgraph/pyqtgraph#1033] opened 2019-09-06 21:37 UTC
### Short description
I am having problems with ImageView & ImageItem when the image consists of integer array with the same values.  This came up for me when all values were zero.
My app is currently Python 2.7 using Anaconda Python, PyQt5 and pyqtgraph 0.10.0

All of my installed packages are given below

### Code to reproduce

from PyQt5.Qt import QApplication
import sys
import numpy as np

#firstImage = np.zeros((1649,1475), dtype=np.int16)
#firstImage = np.zeros((1649,1475), dtype=np.float)
firstImage = np.ones((1649,1475), dtype=np.float)
#firstImage = np.ones((1649,1475), dtype=np.int16)
from pyqtgraph import ImageView

app = QApplication(sys.argv)

imageView = ImageView()
print("type firstImage %s " % type(firstImage))
print("array dtype %s" % firstImage.dtype)
print ("firstImage.min/max %s %s" % (firstImage.min(), firstImage.max()) )
print (firstImage)
print(dir(firstImage))
print("here")
imageView.setImage(firstImage)
print("here")
imageView.show()

sys.exit(app.exec_())

### Expected behavior
This should just simply show ImageView with a flat image

### Real behavior
Here is the output of my code.

bins auto
targetImageSize 200
step: auto
type firstImage <type 'numpy.ndarray'> 
array dtype int16
firstImage.min/max 0 0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__div__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getslice__', '__gt__', '__hash__', '__hex__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__oct__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setslice__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__unicode__', '__xor__', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']
here
/Users/hammonds/anaconda3/envs/miniXES_py2/lib/python2.7/site-packages/pyqtgraph/imageview/ImageView.py:588: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data = data[sl]
bins auto
targetImageSize 200
step: auto
image Shape (1649, 1475)
step (9, 8)
('mx, my,mz', 0, 0, 0.0)
/Users/hammonds/anaconda3/envs/miniXES_py2/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ImageItem.py:471: RuntimeWarning: invalid value encountered in double_scalars
  bins = np.arange(mn, mx+1.01*step, step, dtype=np.int)
Traceback (most recent call last):
  File "/Users/hammonds/anaconda3/envs/miniXES_py2/lib/python2.7/site-packages/pyqtgraph/graphicsItems/HistogramLUTItem.py", line 195, in imageChanged
    h = self.imageItem().getHistogram()
  File "/Users/hammonds/anaconda3/envs/miniXES_py2/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 471, in getHistogram
    bins = np.arange(mn, mx+1.01*step, step, dtype=np.int)
ValueError: arange: cannot compute length
/Users/hammonds/anaconda3/envs/miniXES_py2/bin/pythonw: line 3: 21550 Abort trap: 6           /Users/hammonds/anaconda3/envs/miniXES_py2/python.app/Contents/MacOS/python "$@"
```
An error occurred?
Post the full traceback inside these 'code fences'!
```

### Tested environment(s)

 * PyQtGraph version: 
 * Qt Python binding: 
 * Python version: 
 * NumPy version: 
 * Operating system: 
 * Installation method: 
(minixes_py2) ganges:minixes2 hammonds$ conda list
# packages in environment at /Users/hammonds/anaconda3/envs/minixes_py2:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_0  
backports                 1.0                      py27_1  
backports.functools_lru_cache 1.5                      py27_1  
backports.lzma            0.0.13           py27hd0afa68_0  
backports_abc             0.5              py27h6972548_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py27_0  
ca-certificates           2019.5.15                     1  
certifi                   2019.6.16                py27_1  
cffi                      1.12.3           py27hb5b8e2f_0  
chardet                   3.0.4                    py27_1  
cmarkgfm                  0.4.2            py27h1de35cc_0  
cryptography              2.6.1            py27ha12b0ac_0  
cycler                    0.10.0           py27hfc73c78_0  
dbus                      1.13.6               h90a0687_0  
docutils                  0.14             py27h0befae3_0  
enum34                    1.1.6                    py27_1  
expat                     2.2.6                h0a44026_0  
freetype                  2.9.1                hb4e5f40_0  
functools32               3.2.3.2                  py27_1  
future                    0.17.1                   py27_0  
futures                   3.2.0                    py27_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.2               hd9629dc_0  
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py27_0  
intel-openmp              2019.1                      144  
ipaddress                 1.0.22                   py27_0  
jpeg                      9b                   he5867d9_2  
kiwisolver                1.0.1            py27h0a44026_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.36               ha441bb4_0  
libtiff                   4.0.10               hcb84e12_2  
matplotlib                2.2.3            py27h54f8f79_0  
mkl                       2019.4                      233  
mkl_fft                   1.0.10           py27h5e564d8_0  
mkl_random                1.0.2            py27h27c97d8_0  
ncurses                   6.1                  h0a44026_1  
nose                      1.3.7                    py27_2  
numpy                     1.16.4           py27hacdab7b_0  
numpy-base                1.16.4           py27h6575580_0  
olefile                   0.46                     py27_0  
openssl                   1.1.1c               h1de35cc_1  
pcre                      8.43                 h0a44026_0  
pillow                    5.4.1            py27hb68e598_0  
pip                       19.0.3                   py27_0  
pkginfo                   1.5.0.1                  py27_0  
pycparser                 2.19                     py27_0  
pygments                  2.4.0                      py_0  
pyopenssl                 19.0.0                   py27_0  
pyparsing                 2.3.1                    py27_0  
pyqt                      5.9.2            py27h655552a_2  
pyqtgraph                 0.10.0           py27h28b3542_3  
pysocks                   1.7.0                    py27_0  
python                    2.7.16               h97142e2_0  
python-dateutil           2.8.0                    py27_0  
python.app                2                        py27_9  
pytz                      2018.9                   py27_0  
qt                        5.9.7                h468cd18_1  
readline                  7.0                  h1de35cc_5  
readme_renderer           24.0                     py27_0  
requests                  2.21.0                   py27_0  
requests-toolbelt         0.9.1                      py_0  
scipy                     1.2.1            py27h1410ff5_0  
setuptools                40.8.0                   py27_0  
singledispatch            3.4.0.3          py27he22c18d_0  
sip                       4.19.8           py27h0a44026_0  
six                       1.12.0                   py27_0  
sqlite                    3.27.2               ha441bb4_0  
subprocess32              3.5.3            py27h1de35cc_0  
tk                        8.6.8                ha441bb4_0  
tornado                   5.1.1            py27h1de35cc_0  
tqdm                      4.31.1                   py27_1  
twine                     1.13.0                     py_1  
urllib3                   1.24.2                   py27_0  
webencodings              0.5.1                    py27_1  
wheel                     0.33.1                   py27_0  
wxpython                  3.0                      py27_0  
xz                        5.2.4                h1de35cc_4  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0

**Comment by ixjlyons** [comment] 2019-09-06 22:10
Duplicate of #769. Version 0.11.0 hasn't been released yet, but it will fix this. You could also try [installing from the `develop` branch](https://github.com/pyqtgraph/pyqtgraph#installation-methods).

**Comment by ixjlyons** [comment] 2019-09-06 22:16
Going to close this but let me know if I missed something or you have other issues.

**Closed by ixjlyons** 2019-09-06 22:16 UTC
Labels: duplicate

**Comment by JPHammonds** [comment] 2019-09-06 23:42
Ken,

Thank you.  I tried looking for it in release notes & github issues.  I must have missed it.

John


On Sep 6, 2019 5:17 PM, Kenneth Lyons <notifications@github.com> wrote:

Going to close this but let me know if I missed something or you have other issues.

**Comment by j9ac9k** [comment] 2019-09-07 01:22
We haven't made a new release with the fix yet, hence why you didn't see any documentation on it.

**Comment by JPHammonds** [comment] 2019-09-09 17:23
Note that 0.11 does fix the problem.  Until the release of 0.11 I will convert to a float array.  I need to have easy install for the users.

**Comment by j9ac9k** [comment] 2019-09-09 19:17
@JPHammonds You can install pyqtgraph from the develop branch directly via pip `pip install git+https://github.com/pyqtgraph/pyqtgraph@develop`

If you're using a `requirements.txt` file you put the following line there:

```
git+https://github.com/pyqtgraph/pyqtgraph.git@ad7453c7818eddb3b18354c65370f416cb668b29#egg=pyqtgraph
```

(replace the hash as needed)

I know none of this is optimal vs. a stable release on PyPI; all I can say to that is we're getting there.

**Comment by JPHammonds** [comment] 2019-09-09 19:25
@j9ac9k Thank you for the information.  I will look into this.  I did not mean to convey negative view with my comment.  I realize the complexity of getting a new release together.  I am dealing with that on my own projects.  I meant to convey that I have tested with 0.11 and this fix will work for me.  I have found a way to deal with this using the release version and for now I think that is the best way forward.  It is good to know about pointing to a tag as you have shown in the requirements.txt file.

**Comment by j9ac9k** [comment] 2019-09-09 19:29
@JPHammonds  I did not read your comment as anything negative.  I just meant to relay information that would hopefully be helpful in your present situation (or anyone else that stumbles across here via google)

I too, am dealing with a similar issue with some internal customers at my company; I'm deploying a qt based app with pyqtgraph and not being able to depend on a stable version number, or pypi for a pyqtgraph release has been a constant thorn in my side.  Needless to say, I'm pretty motivated to get the next release out the door as well.
