### ISSUE TITLE
Dragging ROI with Filled Pen leaves tracks

### ISSUE THREAD

**Issue by yamiyukiharu** [pyqtgraph/pyqtgraph#1355] opened 2020-09-03 01:32 UTC
### Short description
Im trying to create a image point based ROI labelling app, hence I used and point ROI with a QPen to fill the inner area with color. However, when I drag the ROI around, it will leave a track behind, it will disappear when I zoom in/out, this process repeats itself when I drag the ROI again. This does not happen if the ROI does not have its area filled.

### Code to reproduce

```python
import pyqtgraph as pg
from PyQt5.QtGui import QPen, QColor, QBrush

pen = QPen()
pen.setBrush(QBrush(QColor(255,0,0)))
roi = pg.ROI((0,0), size=(1,1), pen=pen, resizable=False, removable=True, rotatable=False)
plot = pg.plot()
plot.addItem(roi)
```

### Expected behavior
The ROI should be dragged to the specified position without leaving tracks

### Real behavior
![Annotation 2020-09-03 093340](https://user-images.githubusercontent.com/12526810/92061343-9ce95180-edc8-11ea-807e-91fee4c7ff0e.png)

### Tested environment(s)

 * PyQtGraph version: 0.11.0
 * Qt Python binding: PyQt5 5.15.0 Qt 5.15.0
 * Python version: 3.8.5
 * NumPy version: 1.18.1
 * Operating system: Windows 10
 * Installation method: pip

**Comment by yamiyukiharu** [comment] 2020-09-03 01:35
![image](https://user-images.githubusercontent.com/12526810/92061394-c0ac9780-edc8-11ea-8857-a55652bd7031.png)

**Comment by yamiyukiharu** [comment] 2020-09-03 09:51
Ok i tried to check the source code, it seems that any painting for the ROI has to be WITHIN the bounds of the QRectF, based on the current code:

In ROI.py -> ROI -> paint()

``` python
def paint(self, p, opt, widget):
        # Note: don't use self.boundingRect here, because subclasses may need to redefine it.
        r = QtCore.QRectF(0, 0, self.state['size'][0], self.state['size'][1]).normalized()
        
        p.setRenderHint(QtGui.QPainter.Antialiasing)
        p.setPen(self.currentPen)
        p.translate(r.left(), r.top())
        p.scale(r.width(), r.height())
        p.drawRect(0, 0, 1, 1)
```
The pen provided with a default with of 1 would be painted on the edge of the bounding rect, some parts of the pen's width would spill outside the bounding rect. Hence when the ROI position is updated from a mouse drag event, the "spill over" section would remain.

I tried modifying the code to see paint within the bounding rect, and the problem is gone (this is not the solution)
``` python
def paint(self, p, opt, widget):
        # Note: don't use self.boundingRect here, because subclasses may need to redefine it.
        r = QtCore.QRectF(0, 0, self.state['size'][0], self.state['size'][1]).normalized()
        
        p.setRenderHint(QtGui.QPainter.Antialiasing)
        p.setPen(self.currentPen)
        # p.translate(r.left(), r.top())
        # p.scale(r.width(), r.height())
        p.drawRect(1, 1, self.state['size'][0]-2, self.state['size'][1]-2)
```

**Comment by ixjlyons** [comment] 2020-09-04 04:27
Looks like somewhat of a duplicate of #1141

Note also that there's a convenience function [`mkPen`](https://pyqtgraph.readthedocs.io/en/latest/functions.html#pyqtgraph.mkPen) which helps with pen construction. Importantly, it calls `QPen.setCosmetic`, which maintains the pen's width regardless of painter scaling. I'll add a note to the docs about this.

Thanks for reporting.

**Closed by ixjlyons** 2020-09-04 04:27 UTC
Labels: duplicate
