### ISSUE TITLE
GLScatterPlotItem will hide GLGridItem and GLAxisItem

### ISSUE THREAD

**Issue by ruoyu0088** [pyqtgraph/pyqtgraph#145] opened 2015-02-03 04:05 UTC
After update to 0.9.10, the following example doesn't show GLGridItem:

```
python -m pyqtgraph.examples.GLScatterPlotItem
```

I debuged this and found that OpenGL 3.0.2 works, but OpenGL 3.1.0 doesn't.

**Comment by feketeimre** [comment] 2015-11-15 20:24
Every item that uses GL_LINES or GL_LINE_STRIP becomes invisible after adding a GLScatterPlotItem to the view.
Adding glDisable( GL_TEXTURE_2D ) to the paint function of GLScatterPlotItem just before it returns fixes this problem for me.

**Comment by Thomas00010111** [comment] 2016-03-11 17:52
Just tested the fix proposed by @feketeimre and it worked in my case as well. Is there a reason for not adding this fix to the sources permanently?

**Comment by JanBenes** [comment] 2016-12-28 13:36
Same issue here. The solution proposed by @feketeimre also fixes it for me, thanks Imre. 

Should we make this into a PR to get this looked at/fixed?

**Comment by ixjlyons** [comment] 2019-06-26 17:06
The solution appears to have been merged and I can confirm that the grid is visible in the `GLScatterPlotItem.py` example. Closing.

**Closed by ixjlyons** 2019-06-26 17:06 UTC
Labels: openGL

**Comment by DoC-Noah** [comment] 2019-08-13 16:11
If a GLScatterPlotItem is removed from the GLViewWidget and added back again, the GLGridItems disappear.

**Comment by ixjlyons** [comment] 2019-08-13 16:38
@DoC-Noah would you mind creating a new issue for that? It might have a similar underlying cause, but this specific issue has gone through its lifecycle and seems to be fixed so I'd prefer to leave it closed.

**Comment by DoC-Noah** [comment] 2019-08-13 16:42
Sure thing
