### ISSUE TITLE
PySide6==6.5.1 gives Internal C++ object (PySide6.QtWidgets.QComboBox) already deleted.

### ISSUE THREAD

**Issue by owillebo** [pyqtgraph/pyqtgraph#2737] opened 2023-06-01 11:28 UTC
### Short description

Some PyQtGraph code gives;
`RuntimeError: Internal C++ object (PySide6.QtWidgets.QComboBox) already deleted.`
for PySide6==6.5.1 but not for earlier versions.

### Code to reproduce

```from PySide6.QtWidgets import QApplication
from pyqtgraph import PlotWidget

application = QApplication([])
widget = PlotWidget()
widget.getPlotItem().getViewBox().setMenuEnabled(enableMenu=False)
widget.showGrid(x=True, y=True, alpha=1.0)
widget.show()
application.exec()
```
See also attached code.
[PyQtGraph issue 2737.zip](https://github.com/pyqtgraph/pyqtgraph/files/11624587/PyQtGraph.issue.2737.zip)

### Expected behavior

PyQtGraph not throwing RuntimeErrors

### Real behavior

PyQtGraph throwing RuntimeErrors
```
Traceback (most recent call last):
  File "C:\Program Files\python311\Lib\site-packages\pyqtgraph\WidgetGroup.py", line 221, in <lambda>
    return lambda *args: self.widgetChanged(w, *args)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\python311\Lib\site-packages\pyqtgraph\WidgetGroup.py", line 226, in widgetChanged
    v2 = self.readWidget(w)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\python311\Lib\site-packages\pyqtgraph\WidgetGroup.py", line 257, in readWidget
    val = getFunc(w)
          ^^^^^^^^^^
  File "C:\Program Files\python311\Lib\site-packages\pyqtgraph\WidgetGroup.py", line 35, in comboState
    ind = w.currentIndex()
          ^^^^^^^^^^^^^^^^
RuntimeError: Internal C++ object (PySide6.QtWidgets.QComboBox) already deleted.
```

### Tested environment(s)

 * PyQtGraph version: '0.13.3'
 * Qt Python binding: 'PySide6 6.5.1 Qt 6.5.1'
 * Python version: Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
 * NumPy version: '1.24.3'
 * Operating system: 
 ```Edition		Windows 11 Pro
Version		22H2
Installed on	‎11/‎07/‎2022
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0
```

 * Installation method: pip
numpy==1.24.3
pip==22.3.1
pyqtgraph==0.13.3
PySide6==6.5.1
PySide6-Addons==6.5.1
PySide6-Essentials==6.5.1
setuptools==65.5.0
shiboken6==6.5.1

**Comment by pijyoi** [comment] 2023-06-02 02:05
I can confirm this issue in 0.13.3, however it does not appear on `master`, as the code triggering the `RuntimeError` that you are seeing was replaced in #2694 (prior to the release of PySide6 6.5.1)

Interestingly, #2694 was to fix #2672, which saw a memory leak on PySide6 6.5.0.
PySide6 6.5.1 then included a patch to fix the leak. However, that patch introduced other problems (fixed in #2734), including what you are seeing here.

**Comment by owillebo** [comment] 2023-06-02 13:37
Yep, I confirm that the master runs without this issue.

**Comment by j9ac9k** [comment] 2023-06-02 15:03
Since it's already fixed in master I'm going to close out this issue.  Thanks for the report @owillebo and thanks for the explanation and fix @pijyoi

**Closed by j9ac9k** 2023-06-02 15:03 UTC
