### ISSUE TITLE
SVG exporter places superscripts in odd places

### ISSUE THREAD

**Issue by EfremBraun** [pyqtgraph/pyqtgraph#1881] opened 2021-07-07 16:55 UTC
### Description
When exporting SVGs, superscripts get placed oddly, usually with a big space before them.

### Code to reproduce
```
from PySide2 import QtWidgets
from pyqtgraph import PlotWidget, plot, exporters
import pyqtgraph as pg
import sys

class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)

        self.graphWidget = pg.PlotWidget(title='some quantity in units of 10 <sup> 5 </sup>')
        self.setCentralWidget(self.graphWidget)

        hour = [1,2,3,4,5,6,7,8,9,10]
        temperature = [30,32,34,32,33,31,29,32,35,45]

        # plot data: x, y values
        self.graphWidget.plot(hour, temperature)

        # export
        exp = exporters.SVGExporter(self.graphWidget.plotItem)
        exp.export('contains_superscript.svg')

def main():
    app = QtWidgets.QApplication(sys.argv)
    main = MainWindow()
    main.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()

```

### Real behavior
<img width="1904" alt="Screen Shot 2021-07-07 at 12 54 30 PM" src="https://user-images.githubusercontent.com/6618019/124799393-7f25d500-df22-11eb-8501-4008b157acff.png">

### Tested environment(s)

 * PyQtGraph version: 0.12.1
 * Qt Python binding: PySide2 5.15.2 Qt 5.15.2
 * Python version: 3.7.10
 * NumPy version: 1.19.4
 * Operating system: macOS Catalina 10.15.7

**Comment by j9ac9k** [comment] 2021-07-07 17:50
ooo this is a good one, no clue how to address (I'm not that familiar w/ the exporter code).

**Comment by j9ac9k** [comment] 2023-05-20 03:40
Since I'm looking at another SVG exporter issue, decided to take a look here; not sure _why_ but that superscript is on a separate element it would seem:

```xml
 '\t\t\t<text fill="#969696" fill-opacity="1" stroke="none" '
 'xml:space="preserve" x="4" y="14.625" font-family=".AppleSystemUIFont" '
 'font-size="11" font-weight="400" font-style="normal">some quantity in units '
 'of 10 </text>\n'
 '\t\t\t\n'
 '\n'
 '\t\t\t<text fill="#969696" fill-opacity="1" stroke="none" '
 'xml:space="preserve" x="153.391" y="10.5" font-family=".AppleSystemUIFont" '
 'font-size="7" font-weight="400" font-style="normal">5 </text>\n'
```

This is a segment of the XML from the QGraphicsTextItem that got rendered to the QSvgGenerator and then converted to XML...not sure why it's a whole separate element... or why the x positioning calculation is so off-base...

**Comment by j9ac9k** [comment] 2023-05-20 04:51
If after this line: https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/exporters/SVGExporter.py#L220

I insert the following code, it looks more or less right...

```
        if isinstance(item, QtWidgets.QGraphicsTextItem):
            doc.getElementsByTagName("g")[4].childNodes[3].setAttribute("x", "128.00")
```

By default it's wanting to put the contents too far to the right:

```xml
		<g fill="none" stroke="#969696" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="bevel" transform="matrix(1,0,0,1,258.023,5.5)" font-family=".AppleSystemUIFont" font-size="13" font-weight="400" font-style="normal">
			<text fill="#969696" fill-opacity="1" stroke="none" xml:space="preserve" x="4" y="14.625" font-family=".AppleSystemUIFont" font-size="11" font-weight="400" font-style="normal">some quantity in units of 10</text>
			<text fill="#969696" fill-opacity="1" stroke="none" xml:space="preserve" x="150.172" y="10.5" font-family=".AppleSystemUIFont" font-size="7" font-weight="400" font-style="normal">5</text>
		</g>
```

As can be seen by `x="150.172" ` bit...

I don't know why it's wanting to put the content so far off to the side... it's like there is some empty space it's trying to not overlap or something.

**Comment by j9ac9k** [comment] 2023-05-20 15:53
Again, after going to sleep, there is the [`correctCoordinates`[(https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/exporters/SVGExporter.py#L291) function that appears intended to address this very issue.

**Comment by campagnola** [comment] 2023-05-22 19:02
I wrote a simpler script to make it easier to read the SVG: 
```
import pyqtgraph as pg
app = pg.mkQApp()
w = pg.GraphicsLayoutWidget()
l = pg.LabelItem("test<sup>super</sup>")
w.addItem(l)
w.show()
from pyqtgraph.exporters import SVGExporter
ex = SVGExporter(w.ci)
ex.export('svg_test.svg')
```
Tested on my machine and I can confirm the problem when using chrome to view the SVG:
![image](https://github.com/pyqtgraph/pyqtgraph/assets/940580/eb99b0c3-3683-4d80-9981-d7827feb15b7)
..but it actually looks closer when using inkscape: 
![image](https://github.com/pyqtgraph/pyqtgraph/assets/940580/ef86ebc9-9627-4a31-a36b-837893a51204)

The problem here is that Qt is rendering the superscript using an entirely separate text entity, positioning the superscript based on its assumption about the width of the text. But as we can see, text rendering is unpredictable with SVG, so this assumption will often end up wrong. The correct solution to this is for the superscript to be converted to svg using `baseline-shift = "super"`, but for that we'd need a fix from Qt or for us to write our own SVG generator.

So unfortunately I don't think there is an easy fix for this. In your specific case, you could replace your `<sup>5</sup>` with a unicode exponent ⁵, but that does not generalize beyond simple superscripts / subscripts.

**Comment by j9ac9k** [comment] 2023-05-24 04:41
I'm going to close this issue out as I don't think there is anything for pyqtgraph to do here due to our dependency on Qt's SVG generation functionality.

**Closed by j9ac9k** 2023-05-24 04:41 UTC
Labels: help wanted, need upstream fix, exporters, svg
