### ISSUE TITLE
commit 574c2d2 breaks a lot of PlotDataItem methods

### ISSUE THREAD

**Issue by EfremBraun** [pyqtgraph/pyqtgraph#1652] opened 2021-03-23 14:17 UTC
Commit 574c2d2 / pull request #1619 broke a lot of my code. I have the user being allowed to update the line styles, pens, etc., and all that appeared to stop working.

After looking through it, it appears that this is because PlotDataItem.updateItems() was given the default argument update_style=False. This method is called in many places in PlotDataItem without the update_style argument. For example, setPen(), setSymbol(), etc. In all of these locations, when updateItems() is called, it should be called with update_style=True.

I'm afraid I'm not comfortable enough with the codebase to put in a pull request to fix this, as there are many places in PlotDataItem that updateItems() is called where I'm unsure what the update_style argument should be. It might also be worth seeing where this fell through the cracks in the testing framework.

A contrived minimal working example is below (it was taken from https://www.learnpyqt.com/tutorials/plotting-pyqtgraph/, with 1 line added). Running it under commit 5fa3901 (the prior commit) shows the line widths being updated a few times a second. Running it under commit 574c2d2 shows this not happening.

```
from PySide2 import QtWidgets, QtCore
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg
import sys  # We need sys so that we can pass argv to QApplication
import os
from random import randint

class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)

        self.graphWidget = pg.PlotWidget()
        self.setCentralWidget(self.graphWidget)

        self.x = list(range(100))  # 100 time points
        self.y = [randint(0,100) for _ in range(100)]  # 100 data points

        self.graphWidget.setBackground('w')

        pen = pg.mkPen(color=(255, 0, 0))
        self.data_line =  self.graphWidget.plot(self.x, self.y, pen=pen)

        self.timer = QtCore.QTimer()
        self.timer.setInterval(50)
        self.timer.timeout.connect(self.update_plot_data)
        self.timer.start()

    def update_plot_data(self):

        self.x = self.x[1:]  # Remove the first y element.
        self.x.append(self.x[-1] + 1)  # Add a new value 1 higher than the last.

        self.y = self.y[1:]  # Remove the first 
        self.y.append( randint(0,100))  # Add a new random value.

        self.data_line.setData(self.x, self.y)  # Update the data.

        self.data_line.setPen(width=randint(1,10))  # Update the line widths (added to show issue)


app = QtWidgets.QApplication(sys.argv)
w = MainWindow()
w.show()
sys.exit(app.exec_())
```

**Comment by EfremBraun** [comment] 2021-03-23 14:21
@NilsNemitz @j9ac9k figure you guys want to know.

**Comment by j9ac9k** [comment] 2021-03-23 14:41
Thanks for bringing this to our attention.  I'll try and look into it shortly.

**Comment by j9ac9k** [comment] 2021-03-23 17:21
Just tested this code on #1653 and it looks to be working as intended

**Comment by EfremBraun** [comment] 2021-03-23 18:31
One thing still isn't working. Give me another few minutes and I'll confirm.

**Comment by EfremBraun** [comment] 2021-03-23 18:40
> One thing still isn't working. Give me another few minutes and I'll confirm.

Never mind, that's a separate issue I'm having apparently unrelated to this one. Request #1653 looks like it fixes this!

**Comment by j9ac9k** [comment] 2021-03-23 18:40
Hey @EfremBraun just wanted to give a huge thank you for not only creating this issue, but using pyqtgraph from the master branch and reporting the issue so shortly after that commit was merged.  We are >< close to rolling a new version, and you just prevented a whole lot of head aches for folks.

**Comment by EfremBraun** [comment] 2021-03-23 18:42
My pleasure! I love to help out great open-source projects when I can, and I'm getting far more benefit from having PyQtGraph available to me than I'm providing to PyQtGraph.

**Comment by j9ac9k** [comment] 2021-03-23 18:44
> My pleasure! I love to help out great open-source projects when I can, and I'm getting far more benefit from having PyQtGraph available to me than I'm providing to PyQtGraph.

The timing of this issue you created, was a _huge_ contribution to the project.  As I said, we were on the verge of rolling a new release (might still do it later today 🙊 ); this issue tracker would have been bombarded with this issue. Your timing, and your code to reproduce averted this.  Hopefully this head ache isn't discouraging you from running pyqtgraph from master in the future 😆

**Comment by lidstrom83** [comment] 2021-03-26 17:52
This isn't quite fixed yet. For example:
```
import pyqtgraph as pg
app = pg.mkQApp()
w = pg.PlotWidget()
p = w.plot(x=[0, 1], y=[0, 0], symbol='o', symbolBrush=['g', 'g'])
w.show()
app.exec_()
```
The spots should appear green, but the brushes aren't being set properly. I think this will fail generally when list/array symbol args are passed.

**Comment by j9ac9k** [comment] 2021-03-26 18:40
Tagging @NilsNemitz ☝🏻

**Closed** 2021-03-27 01:01 UTC
