### ISSUE TITLE
Adding points to graph.

### ISSUE THREAD

**Issue by Nikita-Presnov** [pyqtgraph/pyqtgraph#1536] opened 2021-02-02 08:56 UTC
I am very need in one function: adding one point to the PlotDataItem and connecting it with a line to the previous one.
Can I do it here? Or are there other solutions?

**Comment by j9ac9k** [comment] 2021-02-02 17:29
I can't think of a pyqtgraph method that would allow you to insert a point; what I would likely do is insert the point in your numpy array and just re-call the `setData` method on your modified array

**Comment by j9ac9k** [comment] 2021-02-07 02:01
Funny enough, https://github.com/pyqtgraph/pyqtgraph/pull/1453 would address this... we'd like to know more about your use case, if you can provide some code for what your use case looks like and what you wish pyqtgraph would do for you, that would be helpful.

@Nikita-Presnov is there a reason one of the examples in `examples/scrollingPlots.py` won't work for your situation?

**Comment by j9ac9k** [comment] 2021-02-16 15:51
I'm going to close this as a duplicate of #1430 but the above comments should provide some hints with what can be done now in that regard.

**Closed by j9ac9k** 2021-02-16 15:51 UTC
