### ISSUE TITLE
Plot legend font looses size by PNG export at high width parameter

### ISSUE THREAD

**Issue by ikost** [pyqtgraph/pyqtgraph#1767] opened 2021-05-07 09:25 UTC
### Short description
When I export an scene or a plot item from the API or from the context menu to the PNG file, the font of the legend is not as set and shown on the screen. If the width of the export image is big for higher DPI (width > 2000) the axis fonts and plot title font are as shown/as set but the legend font becomes very small as if the font scaling setting is not applied. With lower width (say 600) this behavior is not pronounced.

### Expected behavior
Scale legend font in the exported PNG as on the screen

### Tested environment(s)

 * PyQtGraph version: 12
 * Qt Python binding: PySide2
 * Python version: 5.9.2
 * NumPy version: 
 * Operating system: Windows 10
 * Installation method: pip

### exported image with width = 3000 - look on the legend
![image](https://user-images.githubusercontent.com/20628668/117428087-04dad380-af26-11eb-9572-bc605e916856.png)

### how plot looks in the app on the 4k screen
![image](https://user-images.githubusercontent.com/20628668/117428273-36539f00-af26-11eb-8a4a-1b91f3a5b15b.png)

**Comment by pijyoi** [comment] 2021-05-08 04:44
I find that if I disable the ```ItemIgnoresTransformations``` flag, then the legend text will be correctly sized.
This flag is enabled in https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/LegendItem.py#L68.
Maybe someone knows why it was needed to be enabled?

```python
import numpy as np
import pyqtgraph as pg
import pyqtgraph.exporters

plt = pg.plot()
leg = plt.addLegend()
leg.setFlag(leg.ItemIgnoresTransformations, False)   # the relevant line
plt.plot(3*np.sinc(np.linspace(-3, 1, 1001)), pen='r', name='Hello')
plt.plot(np.sinc(np.linspace(-4, 1, 1001)), pen='g', name='Cruel')
plt.plot(np.sinc(np.linspace(-5, 1, 1001)), pen='b', name='World')

exporter = pg.exporters.ImageExporter(plt.plotItem)
exporter.parameters()['width'] = 2560
exporter.export('export.png')
```

**Comment by j9ac9k** [comment] 2021-05-08 05:04
Duplicate of #1552 (but this one shows a potential fix so I'll leave both open for now)

Doing a git history of that line takes us back to effectively the initial commit of LegendItem.  

Reading the docs on `ItemIgnoresTransformations` I can see why one would think to enable it:

> The item ignores inherited transformations (i.e., its position is still anchored to its parent, but the parent or view rotation, zoom or shear transformations are ignored). This flag is useful for keeping text label items horizontal and unscaled, so they will still be readable if the view is transformed. When set, the item's view geometry and scene geometry will be maintained separately. You must call deviceTransform() to map coordinates and detect collisions in the view. By default, this flag is disabled. This flag was introduced in Qt 4.3.

That said, it's not added to a PlotItem like other objects; so this call might not be needed.

**Comment by j9ac9k** [comment] 2021-10-21 04:53
I'm going to close this issue out as a duplicate of #1552 but as I said in #2028 I have no problem getting rid of it.

**Closed by j9ac9k** 2021-10-21 04:53 UTC
Labels: exporters
